### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by vrgz2022** [Akegarasu/lora-scripts#1]
(lora) root@autodl-container-a1d611953c-8035be35:~/lora-scripts# bash train.sh
prepare tokenizer
update token length: 225
Use DreamBooth method.
prepare train images.
ignore directory without repeats / 繰り返し回数のないディレクトリを無視します: ./train/laohuang/.ipynb_checkpoints
0 train images with repeating.
loading image sizes.
0it [00:00, ?it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (256, 832), count: 0
bucket 1: resolution (256, 896), count: 0
bucket 2: resolution (256, 960), count: 0
bucket 3: resolution (256, 1024), count: 0
bucket 4: resolution (320, 704), count: 0
bucket 5: resolution (320, 768), count: 0
bucket 6: resolution (384, 640), count: 0
bucket 7: resolution (448, 576), count: 0
bucket 8: resolution (512, 512), count: 0
bucket 9: resolution (576, 448), count: 0
bucket 10: resolution (640, 384), count: 0
bucket 11: resolution (704, 320), count: 0
bucket 12: resolution (768, 320), count: 0
bucket 13: resolution (832, 256), count: 0
bucket 14: resolution (896, 256), count: 0
bucket 15: resolution (960, 256), count: 0
bucket 16: resolution (1024, 256), count: 0
/root/miniconda3/envs/lora/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/root/miniconda3/envs/lora/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments / 画像がありません。引数指定を確認してください

**Comment by vrgz2022** [comment]
numbers_conceptname

**Comment by ithomaslin** [comment]
Could you share how you resolve this error? I ran into the same issue.
