### ISSUE TITLE
can kill check  No module named 'triton'  on windows ?

### ISSUE THREAD

**Issue by jvhuaxia** [Akegarasu/lora-scripts#106]
i am a python novice, this check realy reduced  train speed on my pc
there is my gpu usage

0% is this program doing check

![image](https://user-images.githubusercontent.com/29006793/235469337-1dc5fc7d-f4c6-4602-957e-038f666ad14d.png)

**Comment by Akegarasu** [comment]
triton检查不影响速度，他只是显示一行。影响速度的是加载数据
