### ISSUE TITLE
这个有影响什么嘛？ A matching Triton is not available, some optimizations will not be enabled.

### ISSUE THREAD

**Issue by binxu986** [Akegarasu/lora-scripts#107]
win10下运行时：似乎训练还是在往下走？

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
steps:  10%|██████                                                      | 780/7800 [05:04<45:36,  2.57it/s, loss=0.117]epoch 2/10
steps:  15%|█████████

**Comment by Akegarasu** [comment]
不影响
