### ISSUE TITLE
训练GUI错误

### ISSUE THREAD

**Issue by Agreous** [Akegarasu/lora-scripts#108]
**问题**
在训练GUI中启用最小信噪比伽马值选项时，如果输入5或者任何比5大的数字，则GUI不会显示参数预览，也不能正常开始训练

**复现方法**
打开训练GUI,在最小信噪比伽马值选项中输入5或任意比5大的数字，可观察到右侧参数预览内容消失，且无法开始训练

![1](https://user-images.githubusercontent.com/46571579/236645952-e3311b34-fbb6-4f25-aa1d-a8d666f72ea9.png)

![3](https://user-images.githubusercontent.com/46571579/236645957-76b03b4e-bbea-4318-a7fc-5b50e6a13a7c.png)

**环境**
本地部署（python3.10.10,储存库保持最新），autodl镜像（手动同步储存库至最新）

**Comment by Akegarasu** [comment]
已修复
