### ISSUE TITLE
huggingface是不是被墙了

### ISSUE THREAD

**Issue by renqingfei** [Akegarasu/lora-scripts#109]
huggingface访问不了了

**Comment by xsailor511** [comment]
我也是

**Comment by xyzhou-puck** [comment]
+1

**Comment by TousenKaname** [comment]
为什么我给我的服务器挂了clash也不能进入huggingface呢？（docker里挂的clash）

**Comment by renqingfei** [comment]
windows clash可以访问的, 你可能哪里配置的不对

**Comment by TousenKaname** [comment]
> windows clash可以访问的, 你可能哪里配置的不对

我是在linux服务器里的docker挂了个clash，还是进不去，准备去外面挂个clash，真整人，我前天diffuser还跑得好好的，昨天突然连不进去，我以为学校又有什么安全演练ban了，今天才知道huggingface被墙了

**Comment by TousenKaname** [comment]
以后会好吗，有没有懂哥:)

**Comment by L-M-Sherlock** [comment]
https://ping.chinaz.com/huggingface.co

![image](https://user-images.githubusercontent.com/32575846/236750912-3d8d01cb-85d6-4d40-b4d6-5d2031f34686.png)

大部分都寄了

**Comment by renqingfei** [comment]
> 

我中午挂了下clash 可以访问,你那个配置可能不对

**Comment by ze00ro** [comment]
干。

**Comment by renqingfei** [comment]
挂 clash 是可以访问的, 我中午试了
![0d652754428da133d81497db796cb2c](https://user-images.githubusercontent.com/49020588/236753183-a8193803-5899-4f96-9a33-630f95bf04fa.png)

**Comment by renqingfei** [comment]
挂 clash 是可以访问的, 我中午试了

**Comment by QipengZhou** [comment]
现在好像又可以访问了.

**Comment by renqingfei** [comment]
嗯又可以访问了

**Comment by zwluoqi** [comment]
502

**Comment by xsailor511** [comment]
> 挂 clash 是可以访问的, 我中午试了

clash需要花钱吗

**Comment by renqingfei** [comment]
> > 挂 clash 是可以访问的, 我中午试了
> 
> clash需要花钱吗

花钱

**Comment by renqingfei** [comment]
花钱呀

**Comment by xsailor511** [comment]
> 花钱呀

一年多少？

**Comment by renqingfei** [comment]
clash本身不花钱 ,他就是个工具, 是你魔法的那个流量花钱. 每家跟每家不一样,我的是2毛1G 比较贵, 我用的少, 有的包月的也有包年的,这个得自己去了解了
