### ISSUE TITLE
Some module missing in requirements.txt

### ISSUE THREAD

**Issue by tgarm** [Akegarasu/lora-scripts#110]
### How to reproduce:
1. installed via _install.bash_
2. run _run_gui.sh_

### What's wrong

> ModuleNotFoundError: No module named 'uvicorn'

### Possible Reason
It seems in _requirements.txt_, 2 modules are missing:

- uvicorn
- fastapi

### Another issue
In _gui.py_, user can specify host and port which are NOT specifiable using __run_gui.sh__

### Solve
I'd like to make a PR if you may accept.

**Comment by Akegarasu** [comment]
In past, fastapi is required in gradio, which submodule sd-scripts required. Kohya removed it in recent commits, that caused new installation will miss the requirement of fastapi.
