### ISSUE TITLE
xformers 安装失败，没有0.0.19版本

### ISSUE THREAD

**Issue by liyingqiangg** [Akegarasu/lora-scripts#114]
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.2 certifi-2023.5.7 charset-normalizer-3.1.0 filelock-3.12.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.3 pillow-9.5.0 requests-2.30.0 sympy-1.12 torch-2.0.0+cu118 torchvision-0.15.1+cu118 typing-extensions-4.5.0 urllib3-2.0.2
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
ERROR: Could not find a version that satisfies the requirement xformers==0.0.19 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16)
ERROR: No matching distribution found for xformers==0.0.19
xformers 安装失败。

**Comment by x1ntt** [comment]
保证python是3.10.8版本才行，版本不对装不了特定版本的包
