### ISSUE TITLE
GUI运行之后web处是白的

### ISSUE THREAD

**Issue by EkaLinjas** [Akegarasu/lora-scripts#116]
![image](https://github.com/Akegarasu/lora-scripts/assets/125619279/1bde0190-aab6-4d77-9d1e-2d4f3da213ac)
按照流程来的，安装过程中也没有报错，用powershell运行run_gui.ps之后就出现了这种情况
![image](https://github.com/Akegarasu/lora-scripts/assets/125619279/6bb61fcb-9ba7-40aa-8b0d-7e3416f389f0)
点击参数详解之后web变成了这样

**Comment by alpha-xdream** [comment]
[pull/121](https://github.com/Akegarasu/lora-scripts/pull/121) 你可以试下这个pr
