### ISSUE TITLE
如何进行多卡训练？

### ISSUE THREAD

**Issue by k352483506** [Akegarasu/lora-scripts#120]
如何才能多卡并行进行训练

**Comment by martellz** [comment]
https://github.com/Akegarasu/lora-scripts/blob/7de15d64f4641fd88c6bd90a327d6c15a3391866/train.sh#L73
(train.sh好像漏了一行设置multi-gpu变量，自己加上叭)

**Comment by gaogg** [comment]
加上出现了这个错误[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).

**Comment by 1224wxwx** [comment]
@martellz 我加行了multi_gpu，但是仍然只跑在一张卡上...请问你是加了就成功多卡运行了吗？

**Comment by martellz** [comment]
@1224wxwx  我没尝试过，群友以前遇到过，就是在 accelerate launch 加上 --multi_gpu 
你的多卡是什么情况呢？

**Comment by martellz** [comment]
刚在autodl测完，再加上--num_processes=2
`accelerate launch --multi_gpu --num_processes=2 ...`

**Comment by k352483506** [comment]
![Uploading 33.png…]()
@martellz 您的方法是有效的，如果使用的最新版的界面需要这样添加：
路径：/gui.py  76行
改为如下：
`def run_train(toml_path: str):
    print(f"Training started with config file / 训练开始，使用配置文件: {toml_path}")
    args = [
        sys.executable, "-m", "accelerate.commands.launch", 
        "--multi_gpu",
        "--num_processes", "2",
        "--num_cpu_threads_per_process", "8",
        "./sd-scripts/train_network.py",
        "--config_file", toml_path,
    ]`

**Comment by k352483506** [comment]
@martellz 您的方法是有效的，如果使用的最新版的界面需要这样添加： 路径：/gui.py 76行
改为如下：
![33](https://github.com/Akegarasu/lora-scripts/assets/59390305/a878d79e-ed8e-49bb-80a1-81f69a180542)

**Comment by SrlyNb666** [comment]
> 



> 同样跑一个卡

简单，在train.sh文件的52行，就是clip_skip=2 下面一行加上multi_gpu=1 ，然后在hungface文件夹里面的huggingface文件里的一个配置文件里，就是default_config文件里把17行的1改成2
