### ISSUE TITLE
云端服务器启动报错

### ISSUE THREAD

**Issue by baifagg** [Akegarasu/lora-scripts#122]
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/d8f2c2f3-5cf1-4402-9c7f-0ff684c5335c)
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/bfc57df2-dfc3-4c0d-9bcc-52b3989f759e)
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/ce08e061-d899-4024-b3ab-a8a1164f869a)
显示一个大大的图标，没有界面

**Comment by baifagg** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/aeab42f1-2f42-42cf-9ade-ccbec235a613)

**Comment by martellz** [comment]
首先127.0.0.1是环回地址，访问不到云服务器的捏。
其次网页(居然还能)显示一个大大的图标，是不是你本地也启了服务？
服务器先老老实实用命令行叭。

**Comment by baifagg** [comment]
> 

点击环回地址阿里云会把这个地址转换成公网可访问的地址。主要是这个界面太绷不住了。而且命令行我也运行失败了，我下午贴一下报错

**Comment by baifagg** [comment]
> 
就是将7860这个端口映射出来吧 ，这我也不知道啊，但我平时在自己电脑上部署的应用，防火墙开放端口之后，使用我家的公网地址加对应端口也是可以访问的

**Comment by martellz** [comment]
平时只能用0.0.0.0，阿里云能把127.0.0.1映射出来我没想到。总之先不纠结这个，我看这个前端就是一个静态页面吧，
总不能是网不好/带宽低吧...

**Comment by baifagg** [comment]
> 平时只能用0.0.0.0，阿里云能把127.0.0.1映射出来我没想到。总之先不纠结这个，我看这个前端就是一个静态页面吧， 总不能是网不好/带宽低吧...

不会是这些原因，我部署的sd是可以正常使用的。我感觉就是网页文件有问题，没有正常安装或者加载。但是sd又可以正常使用的。我还是使用命令行吧，毕竟是云端，排错不容易

**Comment by Akegarasu** [comment]
无法复现。出现这种情况应该是你的网页没有加载完全，请抓包查看是否有无法加载的部分。

**Comment by Xibai-Sike** [comment]
阿里云 dsw 对127.0.0.1, 0.0.0.0等本地ip有特殊处理。 
 1. 点击terminal 中的 http://127.0.0.1:8080,  新标签页打开 https://dsw-gateway-cn-hangzhou.data.aliyun.com/dsw-{id}/proxy/8080/
 2. 很多 web app 里 link resource(css, js, png etc..)  ， 它们的 link url 可能是以/ 为前缀， 这样就请求不到资源。阿里云通过注入/proxyAssets.js 解决了部分的问题。

这种情况应该是 web app 里的静态资源路径不对

**Comment by dorado-lmz** [comment]
@Akegarasu  大佬，frontend 项目中的 html 对静态资源的引用使用绝对路径，而阿里云只支持相对路径，因此页面加载不了。能不能把 fontend的 publicPath 改成 './'

![image](https://github.com/Akegarasu/lora-scripts/assets/7953958/a4db993a-207d-425f-94e9-a1b1cb3badb5)

**Comment by Akegarasu** [comment]
fixed
