### ISSUE TITLE
Enhancement: Open GUI to public URL

### ISSUE THREAD

**Issue by novitae** [Akegarasu/lora-scripts#126]
Some people (as me) are running all of those stable diffusion scripts on distant computers in order to have more performant devices at disposition. Since [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and [bmaltais/kohya_ss](https://github.com/bmaltais/kohya_ss) are using `gradio` for their ui, it has a builtin functionality open the link to the public, and create a link as `https://af[...]83.gradio.app` in order to access it if we're not directly on the computer (so we can't access localhost). I think it would be nice to implement that here. Thanks

**Comment by eulancer** [comment]
I would also like to get the ability to share to a public link

**Comment by ai-vip** [comment]
open gui.sh and change the default host

parser.add_argument("--host", type=str, default="0.0.0.0")
