### ISSUE TITLE
为什么wandb里没有loss/epoch的图 是缺少代码还是wandb的设置问题

### ISSUE THREAD

**Issue by baifagg** [Akegarasu/lora-scripts#129]
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/2681b3b4-9f30-4bec-b09e-22602410591a)

**Comment by baifagg** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/48c06515-7119-4c8b-b56f-388e10d014c3)

**Comment by Akegarasu** [comment]
自己打开生成预览图的选项才会有

**Comment by baifagg** [comment]
> 自己打开生成预览图的选项才会有

我确定我每次都是打开的 但是还是没有这个值
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/fa30f53c-697f-4c90-afe8-d869fc768557)

**Comment by baifagg** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/51266591/da96e587-f237-4712-a8fa-2b70f0c953cf)
