### ISSUE TITLE
sd2.1 768如何训练lora

### ISSUE THREAD

**Issue by gaogg** [Akegarasu/lora-scripts#130]
请教一下我把训练脚本train.sh中is_v2_model设成1，parameterization=1训练sd2.1-768，但是loss一直不收敛（>0.3），请教一下是还需要改哪里吗？

**Comment by Georgebillion** [comment]
收敛吗？你几个学习率设置是不是太小了？检查一下

**Comment by gaogg** [comment]
不收敛，我学习率设置和sd1.5一样的，sd1.5以及sd2.1 512 loss都在0.1上下，但是sd2.1 768loss就一直不太正常

**Comment by Georgebillion** [comment]
加大学习率还是不收敛？
