### ISSUE TITLE
No module named 'accelerate

### ISSUE THREAD

**Issue by JesChen** [Akegarasu/lora-scripts#132]
D:\Assistance\sd-webui-aki\sd-webui-aki-v4\lora-scripts-main\lora-scripts-main\venv\Scripts\python.exe: Error while finding module specification for 'accelerate.commands.launch' (ModuleNotFoundError: No module named 'accelerate')
Train finished

Not able to train.

**Comment by rabbitxl** [comment]
but， why when i run in webui there's no need to install python?
