### ISSUE TITLE
请问如何将tensorboard监听到任意地址而不是回环地址

### ISSUE THREAD

**Issue by r970707452c** [Akegarasu/lora-scripts#138]

**Comment by r970707452c** [comment]
没事了解决了，将run.py中的
subprocess.Popen([sys.executable, "-m", "tensorboard.main", "--logdir", "logs", "--port", str(args.tensorboard_port)])
改成
subprocess.Popen([sys.executable, "-m", "tensorboard.main", "--host", "0.0.0.0", "--logdir", "logs", "--port", str(args.tensorboard_port)])

**Comment by r970707452c** [comment]
但改了以后访问tensorboard还是会访问到127.0.0.1，请问这部分应该去哪里修改

**Comment by emetzodiac** [comment]
去前端里面改html和js

**Comment by Akegarasu** [comment]
这部分会改进

**Comment by Akegarasu** [comment]
已更新。使用 `--tensorboard-host` 指定。并且可以在ui界面中修改打开的网址
![image](https://github.com/Akegarasu/lora-scripts/assets/36563862/6812f6eb-8e4e-4fc6-babd-aced39d37916)

**Comment by xiao-keeplearning** [comment]
大佬，问下这个怎么设置？
比如我运行时`run_gui.sh`时指定 --host 10.10.10.10 --port 8000 --tensorboard-host 10.10.10.10，这个UI应该是10.10.10.10 ,port 还是 6006，是这样么？
