### ISSUE TITLE
训练时报这个错误，是有什么没安装或者升级吗？

### ISSUE THREAD

**Issue by wuyaowang1210** [Akegarasu/lora-scripts#141]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\ai\lora-scripts-gui\sd-scripts\train_network.py:783 in <module>                               │
│                                                                                                  │
│   780 │   args = parser.parse_args()                                                             │
│   781 │   args = train_util.read_config_from_file(args, parser)                                  │
│   782 │                                                                                          │
│ ❱ 783 │   train(args)                                                                            │
│   784                                                                                            │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\sd-scripts\train_network.py:610 in train                                  │
│                                                                                                  │
│   607 │   │   │   │                                                                              │
│   608 │   │   │   │   # Predict the noise residual                                               │
│   609 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 610 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   611 │   │   │   │                                                                              │
│   612 │   │   │   │   if args.v_parameterization:                                                │
│   613 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\util │
│ s\operations.py:521 in forward                                                                   │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\util │
│ s\operations.py:509 in __call__                                                                  │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\amp\autocast_mode.py:14 in                 │
│ decorate_autocast                                                                                │
│                                                                                                  │
│    11 │   @functools.wraps(func)                                                                 │
│    12 │   def decorate_autocast(*args, **kwargs):                                                │
│    13 │   │   with autocast_instance:                                                            │
│ ❱  14 │   │   │   return func(*args, **kwargs)                                                   │
│    15 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    16 │   return decorate_autocast                                                               │
│    17                                                                                            │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\diffusers\model │
│ s\unet_2d_condition.py:582 in forward                                                            │
│                                                                                                  │
│   579 │   │   down_block_res_samples = (sample,)                                                 │
│   580 │   │   for downsample_block in self.down_blocks:                                          │
│   581 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 582 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   583 │   │   │   │   │   hidden_states=sample,                                                  │
│   584 │   │   │   │   │   temb=emb,                                                              │
│   585 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\diffusers\model │
│ s\unet_2d_blocks.py:837 in forward                                                               │
│                                                                                                  │
│    834 │   │   │   │   )[0]                                                                      │
│    835 │   │   │   else:                                                                         │
│    836 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│ ❱  837 │   │   │   │   hidden_states = attn(                                                     │
│    838 │   │   │   │   │   hidden_states,                                                        │
│    839 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                          │
│    840 │   │   │   │   │   cross_attention_kwargs=cross_attention_kwargs,                        │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\diffusers\model │
│ s\transformer_2d.py:265 in forward                                                               │
│                                                                                                  │
│   262 │   │                                                                                      │
│   263 │   │   # 2. Blocks                                                                        │
│   264 │   │   for block in self.transformer_blocks:                                              │
│ ❱ 265 │   │   │   hidden_states = block(                                                         │
│   266 │   │   │   │   hidden_states,                                                             │
│   267 │   │   │   │   encoder_hidden_states=encoder_hidden_states,                               │
│   268 │   │   │   │   timestep=timestep,                                                         │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\diffusers\model │
│ s\attention.py:291 in forward                                                                    │
│                                                                                                  │
│   288 │   │                                                                                      │
│   289 │   │   # 1. Self-Attention                                                                │
│   290 │   │   cross_attention_kwargs = cross_attention_kwargs if cross_attention_kwargs is not   │
│ ❱ 291 │   │   attn_output = self.attn1(                                                          │
│   292 │   │   │   norm_hidden_states,                                                            │
│   293 │   │   │   encoder_hidden_states=encoder_hidden_states if self.only_cross_attention els   │
│   294 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: replace_unet_cross_attn_to_xformers.<locals>.forward_xformers() got an unexpected keyword argument
'encoder_hidden_states'
steps:   0%|                                                                                  | 0/3750 [00:23<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\ai\lora-scripts-gui\python\lib\runpy.py:196 in _run_module_as_main                            │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ G:\ai\lora-scripts-gui\python\lib\runpy.py:86 in _run_code                                       │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\comm │
│ ands\launch.py:928 in <module>                                                                   │
│                                                                                                  │
│   925                                                                                            │
│   926                                                                                            │
│   927 if __name__ == "__main__":                                                                 │
│ ❱ 928 │   main()                                                                                 │
│   929                                                                                            │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\comm │
│ ands\launch.py:924 in main                                                                       │
│                                                                                                  │
│   921 def main():                                                                                │
│   922 │   parser = launch_command_parser()                                                       │
│   923 │   args = parser.parse_args()                                                             │
│ ❱ 924 │   launch_command(args)                                                                   │
│   925                                                                                            │
│   926                                                                                            │
│   927 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\comm │
│ ands\launch.py:918 in launch_command                                                             │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\accelerate\comm │
│ ands\launch.py:580 in simple_launcher                                                            │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['G:\\ai\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py',
'--config_file', 'G:\\ai\\lora-scripts-gui\\toml\\autosave\\20230601-141441.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by martellz** [comment]
https://github.com/Akegarasu/lora-scripts/issues/27#issuecomment-1464857307

**Comment by LeeLexHong** [comment]
同问哦哦

**Comment by niLIjia** [comment]
同问

**Comment by Akegarasu** [comment]
#27
