### ISSUE TITLE
GTX TITAN X 12G 训练时候GPU10G的时候屏幕就黑了，失败告终，错误信息如下：

### ISSUE THREAD

**Issue by anitaihua** [Akegarasu/lora-scripts#148]
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)

**Comment by Akegarasu** [comment]
黑和失败没关系 报错应该是xformers不兼容
