### ISSUE TITLE
 Error(s) in loading state_dict for UNet2DConditionModel

### ISSUE THREAD

**Issue by zhixideyu** [Akegarasu/lora-scripts#150]
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
        
请问一下这个怎么解决呢？

**Comment by chaozwn** [comment]
how to solve it?

**Comment by Pevernow** [comment]
+1

**Comment by zhixideyu** [comment]
> +1

<img width="779" alt="image" src="https://github.com/Akegarasu/lora-scripts/assets/39975240/7f878c7d-0dc3-46da-b4af-2fce2126c70d">
