### ISSUE TITLE
训练开始ModuleNotFoundError: No module named 'accelerate

### ISSUE THREAD

**Issue by ILOVEHUMAN** [Akegarasu/lora-scripts#152]
D:\stable diffusion\lora\lora-scripts-main\lora-scripts-main\venv\Scripts\python.exe: 
Error while finding module specification for 'accelerate.commands.launch' (ModuleNotFoundError: No module named 'accelerate')
怎么解决

**Comment by quryq** [comment]
这个问题，要么是没有运行install.ps1，要么就是在运行过程失败了，建议按照下面操作一下：
1. 切换到lora-scripts文件夹
2. 重新运行install.ps1

**Comment by Cocteau86** [comment]
我这里不知道是因为对应的库没了还是怎么，安装不了xformer，有能替换和更改的方法吗
所在位置 行:36 字符: 5
+     pip install -U -I --no-deps xformers==0.0.21
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Skippi..., and text/html:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: Could not find a version that satisfies the requirement xformers==0.0.21 (from versions: none)
ERROR: No matching distribution found for xformers==0.0.21
xformers 安装失败。
安装失败。
