### ISSUE TITLE
使用gui版本训练报错

### ISSUE THREAD

**Issue by Jacko07** [Akegarasu/lora-scripts#166]
备注:已经使用A强制更新-国内加速更新到最新版;  win10,python 3.10.8; 模型应该是v2,(因为下载来名称里就带了V2...);使用的基本是默认配置;图片裁剪的是512x640

使用目录内的 python 进行启动....
Starting tensorboard...
Server started at http://127.0.0.1:28000
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
Training started with config file / 训练开始，使用配置文件: E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\toml\autosave\20230626-002205.toml
Loading settings from E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\toml\autosave\20230626-002205.toml...
E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\toml\autosave\20230626-002205
prepare tokenizer
update token length: 255
Using DreamBooth method.
prepare images.
found directory train\hyc\6_hyc contains 40 image files
240 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 640)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "train\hyc\6_hyc"
    image_count: 40
    num_repeats: 6
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: hyc
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 3075.85it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 640), count: 240
mean ar error (without repeats): 0.0
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: ./sd-models/lofi_V2.safetensors
Traceback (most recent call last):
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1114, in <module>
    main()
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1110, in main
    launch_command(args)
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\Code_Docs\AI\sd\Lora\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Code_Docs\\AI\\sd\\Lora\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'E:\\Code_Docs\\AI\\sd\\Lora\\lora-scripts-gui\\toml\\autosave\\20230626-002205.toml']' returned non-zero exit status 3221225477.
Training failed / 训练失败

**Comment by Georgebillion** [comment]
网页GUI页面应该有说明，启用V2模型的同时，启用参数化参数
