### ISSUE TITLE
network module key error = locon

### ISSUE THREAD

**Issue by aigias** [Akegarasu/lora-scripts#171]
Hi Akegarasu,
才更新过仓库。
训练时选择lycoris，lycoris_algo选择locon(下拉菜单显示为locon)，训练启动后报错：key error = locon
我记得选locon的话，这个值在以前版本传的是"lora"，请看看，感谢

**Comment by Akegarasu** [comment]
locon是可以的，请提供完整报错

**Comment by aigias** [comment]
训练的错误日志和参数如下：

![image](https://github.com/Akegarasu/lora-scripts/assets/126138404/f5c1c28c-6d94-4404-917d-9f27d8363552)

![image](https://github.com/Akegarasu/lora-scripts/assets/126138404/fd176beb-1559-493e-9355-bd80e41875a1)

在使用脚本训练该任务时，$algo = "locon"，会报同样错误。
$algo = "lora"时，不会出现报错。

$algo = "lora" # LyCORIS network algo | LyCORIS 网络算法 可选 lora、loha、lokr、ia3、dylora。lora即为locon
脚本注释也有提到。

**Comment by Akegarasu** [comment]
非bug，你的lycoris版本过低

**Comment by aigias** [comment]
更新了依赖，正常了，感谢。
