### ISSUE TITLE
云平台使用（wd14-tagger）会一直卡在`Installing onnxruntime`

### ISSUE THREAD

**Issue by yl-yue** [Akegarasu/lora-scripts#174]
云平台使用（wd14-tagger）会一直卡在`Installing onnxruntime`，开学术加速与不开学术加速，都没用

**Comment by BigKunLun** [comment]
AutoDL 上遇到同样的问题，怎么解决的？

**Comment by Sheldongg** [comment]
已经安装了onnxruntime-gpu但是报错
15:11:23-804488 WARNING  Package version not found: onnxruntime
Installing onnxruntime
