### ISSUE TITLE
错误：无法打开需求文件：[Errno 2] 没有这样的文件或目录：“requirements.txt”

### ISSUE THREAD

**Issue by MS666666** [Akegarasu/lora-scripts#176]
![2023-07-15 03-01-09-74](https://github.com/Akegarasu/lora-scripts/assets/44149537/299841e0-7ef6-47b5-8458-60931d8f719a)
大佬们这个问题怎么解决

**Comment by SAKURA-CAT** [comment]
你需要在clone的时候安装子模块：
```
git clone --recursive 项目链接
```
或者clone下来以后在项目根目录执行git命令：
```
git submodule init
git submodule update
```
