### ISSUE TITLE
install 的时候出错

### ISSUE THREAD

**Issue by supterSun** [Akegarasu/lora-scripts#181]
运行install.bash的时候报错
Creating python venv...
active venv
Installing torch & xformers...
install.bash: line 27: nvcc: command not found
Cuda Version:
Unsupported cuda version:
版本信息
1.13.1+cu117
11.7
8500
大佬看看啥问题

**Comment by humiao1993** [comment]
你的环境问题。你需要增加nvcc的环境变量

**Comment by Akegarasu** [comment]
安装cuda
