### ISSUE TITLE
vae的state_dict要换一下keys

### ISSUE THREAD

**Issue by af-74413592** [Akegarasu/lora-scripts#186]
可能是diffusers的问题，代码我已经改好了。sd-script/library/model_utils.py 871行改为
    missing_keys = ["encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias"]
    origin_keys = ["encoder.mid_block.attentions.0.query.weight","encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.key.weight" ,"encoder.mid_block.attentions.0.key.bias","encoder.mid_block.attentions.0.value.weight",  "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.proj_attn.weight","encoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.query.bias","decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.key.bias","decoder.mid_block.attentions.0.value.weight","decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.proj_attn.weight","decoder.mid_block.attentions.0.proj_attn.bias"]
    converted_vae_checkpoint_fix = {}
    swich_key_dict = {ok:mk for ok,mk in zip(origin_keys,missing_keys)}
    for key in converted_vae_checkpoint.keys():
        if key in origin_keys:
            newkey = swich_key_dict[key]
            converted_vae_checkpoint_fix[newkey] = converted_vae_checkpoint[key]
        else:
            converted_vae_checkpoint_fix[key] = converted_vae_checkpoint[key]
    info = vae.load_state_dict(converted_vae_checkpoint_fix)

**Comment by af-74413592** [comment]
确定是diffusers版本问题，0.14.0就不用换，高版本还有其他bug。

**Comment by af-74413592** [comment]
最好出一个requirements.txt

**Comment by af-74413592** [comment]
diffusers版本还是不对，得降到0.10.0

**Comment by af-74413592** [comment]
acclerate是0.18.0

**Comment by humiao1993** [comment]
兄弟， 我安装你的方式开始没有解决呢 。可以吧你修改之后的代码放出来看看吗？

**Comment by af-74413592** [comment]
> 

我最后就是通过降版本实现的，用高版本的diffusers除了这一处还有其他的bug 后面我也没改出来 建议还是降版本。

**Comment by af-74413592** [comment]
总体来说 这一套代码太老了 后续没有维护更新 diffusers库也在不断更新 后面适配会更麻烦的。

**Comment by humiao1993** [comment]
我直接去用sd-script训练了。没用这个了。

**Comment by WudiJoey** [comment]
> 我直接去用sd-script训练了。没用这个了。

nsdd, 使用最新的sd-script加上这个仓库里的train.sh可以直接跑的

**Comment by huangerlin** [comment]
这个有解决方案了吗，我也遇到问题了

**Comment by Akegarasu** [comment]
diffusers 0.18.2 未出现此问题
