### ISSUE TITLE
SDXL 1.0 Lora 训练报错

### ISSUE THREAD

**Issue by Jon-Zbw** [Akegarasu/lora-scripts#200]
epoch 1/5
/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/venv/lib/python3.9/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/./sdxl_train_network.py", line 174, in <module>
    trainer.train(args)
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/train_network.py", line 775, in train
    noise_pred = self.call_unet(
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/./sdxl_train_network.py", line 154, in call_unet
    noise_pred = unet(noisy_latents, timesteps, text_embedding, vector_embedding)
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/venv/lib/python3.9/site-packages/accelerate/utils/operations.py", line 521, in forward
    return model_forward(*args, **kwargs)
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/venv/lib/python3.9/site-packages/accelerate/utils/operations.py", line 509, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/venv/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/bowen/zhang3/LDM/lora-scripts/sd-scripts/library/sdxl_original_unet.py", line 1080, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 58 but got size 57 for tensor number 1 in the list.
steps:   0%|                                                                                                                                                                                         | 0/100 [00:02<?, ?it/s]

**Comment by WuNein** [comment]
你要不要试试看，sd-scripts换到这个分支上https://github.com/kohya-ss/sd-scripts/tree/sdxl 

我几个月不弄，感觉已经过分复杂了

**Comment by Jon-Zbw** [comment]
就是在此分支下报的错，排查出问题出在设置了bucket_no_upscale=true

**Comment by WuNein** [comment]
https://github.com/kohya-ss/sd-scripts/issues/713 这个是吧，我晚点空了试试看！谢谢你！

**Comment by Jon-Zbw** [comment]
对的，我补充了当时报错的参数， 谢谢

**Comment by WuNein** [comment]
对了，您能不能分享一个完整的训练脚本，比如train.sh train.ps1

**Comment by Jon-Zbw** [comment]
我是直接跑的 sdxl_train_network.py

**Comment by Jon-Zbw** [comment]
pretrained_model_name_or_path =""	
dataset_config ="C:\\lora\\dataset_config.toml" 
sample_prompts = "./prompt.txt" 
output_dir = "./lora\\model" 
logging_dir = "c:\lora\llog" 
output_name = "libsp" 
train_batch_size=1 
network_dim =16 
network_alpha =8
max_train_steps = 1620 
save_every_n_steps = 162 
sample_every_n_steps = 162 
optimizer_type = "adafactor"
optimizer_args=["scale_parameter=False","relative_step=False","warmup_init=False" ] 
lr_scheduler_num_cycles = 6
lr_scheduler = "constant_with_warmup"
lr_warmup_steps= 162
network_train_unet_only = true 
learning_rate=4e-7 
unet_lr = 4e-7
text_encoder_lr =0.0001 
caption_extension =".txt" 
resolution="1024,1024"
save_precision ="fp16" 
mixed_precision ="fp16" 
sample_sampler ="euler_a"
network module="networks.lora" 
max_token_length=225 
bucket_reso_steps=32 
cache latents=true 
enable_bucket=true
###bucket_no_upscale=true 后面就是注释了这个，修改了min_bucket_reso=640、max_bucket_reso=1024、 
                                                          resolution="1024,1024"还有数据集也resize成640*256，之后就可以跑起来了
xformers=false
persistent data loader workers=true 
gradient_checkpointing=true
cache_text_encoder_outputs=true 
no_half_vae = true

**Comment by WuNein** [comment]
谢谢~我也跑起来了~
```
[model_arguments]
v2 = false
v_parameterization = false
vae = "/data/stable-diffusion-webui/models/Stable-diffusion/sdxl/sd_xl_base_1.0.vae.safetensors"
pretrained_model_name_or_path = "/data/stable-diffusion-webui/models/Stable-diffusion/sdxl/sd_xl_base_1.0.safetensors"

[dataset_arguments]
train_data_dir = "/data/all_train"
reg_data_dir = ""
resolution = "512,768"
prior_loss_weight = 1

[additional_network_arguments]
network_dim = 32
network_alpha = 16
network_train_unet_only = true
network_train_text_encoder_only = false
network_module = "networks.lora"
network_args = []

[optimizer_arguments]
unet_lr = 1e-4
text_encoder_lr = 1e-5

optimizer_type = "adafactor"
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_restart_cycles = 1

[training_arguments]
train_batch_size = 2
noise_offset = 0.0
keep_tokens = 0
min_bucket_reso = 512
max_bucket_reso = 1024
caption_extension = ".txt"
max_token_length = 225
seed = 1337
xformers = true
lowram = false
max_train_epochs = 10
resolution = "1024,1024"
clip_skip = 2
mixed_precision = "fp16"

[sample_prompt_arguments]
sample_sampler = "euler_a"
sample_every_n_epochs = 5

[saving_arguments]
output_name = "output_name"
save_every_n_epochs = 1
save_state = false
save_model_as = "safetensors"
output_dir = "./output"
logging_dir = "./logs"
log_prefix = ""
save_precision = "fp16"

[others]
cache_latents = true
shuffle_caption = true
enable_bucket = true
bucket_reso_steps=32
no_half_vae = true
bucket_no_upscale = false
```

```
python -m accelerate.commands.launch ${launchArgs[@]} --num_cpu_threads_per_process=8 "./sd-scripts/sdxl_train_network.py" \
  --config_file=$config_file \
  --sample_prompts=$sample_prompts \
  ${extArgs[@]}
```
我就非常疑惑这个vae一定要no_half_vae

**Comment by HenryBao91** [comment]
> 

你好，请问一下怎么训练 sdxl 大模型呢？

**Comment by Jon-Zbw** [comment]
现在应该有finetune的项目吧，你找下，要求不高的话用lora足够了

**Comment by Jon-Zbw** [comment]
> > 
> 
> 你好，请问一下怎么训练 sdxl 大模型呢？

现在应该有finetune的项目吧，你找下，要求不高的话用lora足够了
