### ISSUE TITLE
不管如何调试都是这样报错

### ISSUE THREAD

**Issue by gigapooh** [Akegarasu/lora-scripts#203]
Loading settings from D:\novelai\lora2\toml\autosave\20230810-151251.toml...
D:\novelai\lora2\toml\autosave\20230810-151251
prepare tokenizer
update token length: 255
Using DreamBooth method.
prepare images.
0 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

[Dataset 0]
loading image sizes.
0it [00:00, ?it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
D:\novelai\lora2\python\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\novelai\lora2\python\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります）
Training finished / 训练完成

**Comment by yyx0701** [comment]
没有数据，你的文件夹路径填错了

**Comment by gigapooh** [comment]
> 
如果填错的话是模型还是训练集？
