### ISSUE TITLE
Ubuntu下gui异常

### ISSUE THREAD

**Issue by jj-a-li** [Akegarasu/lora-scripts#205]
![屏幕截图 2023-08-11 223237](https://github.com/Akegarasu/lora-scripts/assets/72844255/beb37fb5-b128-4e51-bfac-46062e6149e5)
这个gui界面在Ubuntu下启动是有问题的，只能用train.sh
更新了这么多版本也无法使用，现在加上sdxl只更新在gui上，那就没法搞了
No permission, wrong errorCode, please login first
Invalid request url: /
Invalid request url: /tensorboard.md
Invalid request url: /tagger.md

**Comment by Akegarasu** [comment]
it works well in ubuntu. check the error log in browser development tool "network" tab.

**Comment by jj-a-li** [comment]
> it works well in ubuntu. check the error log in browser development tool "network" tab.



> it works well in ubuntu. check the error log in browser development tool "network" tab.
![17](https://github.com/Akegarasu/lora-scripts/assets/72844255/8663b65b-5f8d-4d82-97b4-de0a360100d5)
so i add this
![44](https://github.com/Akegarasu/lora-scripts/assets/72844255/a5e72197-3df1-413f-8501-8dd66962b083)
however
still much error

![屏幕截图 2023-08-12 110813](https://github.com/Akegarasu/lora-scripts/assets/72844255/80e267d2-7ab5-417e-8d14-d56e54d37180)

**Comment by jj-a-li** [comment]
> #122


这样手工改一遍，大概率没法彻底，像这边一启动首先来个404，训练曲线那一页是空白
可能会导致问题
训练已经可以启动
