### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AutoencoderKL

### ISSUE THREAD

**Issue by hanggun** [Akegarasu/lora-scripts#213]
![image](https://github.com/Akegarasu/lora-scripts/assets/39485441/a2dac423-a6e1-4e66-b4bf-b34e96c41a4b)

求大神指导，在ubuntu18.04上更新了代码，将diffusers更新到0.18.3版本就爆VAE加载错误，但是原来使用的diffusers版本0.10.0就不报错，这该怎么解决呀

**Comment by Akegarasu** [comment]
有一说一，这个是老毛病了 diffusers那边一直没解决
