### ISSUE TITLE
求救:RuntimeError: CUDA error: the launch timed out and was terminated CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by 2256593769** [Akegarasu/lora-scripts#216]
create LoRA network. base dim (rank): 32, alpha: 32
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
bin A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
use 8-bit AdamW optimizer | {}
override steps. steps for 10 epochs is / 指定エポックまでのステップ数: 301400
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 30140
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 30140
  num epochs / epoch数: 10
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 301400
steps:   0%|                                                                                | 0/301400 [00:00<?, ?it/s]
epoch 1/10
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\sd-scripts\train_network.py:990 in <module>    │
│                                                                                                  │
│   987 │   args = train_util.read_config_from_file(args, parser)                                  │
│   988 │                                                                                          │
│   989 │   trainer = NetworkTrainer()                                                             │
│ ❱ 990 │   trainer.train(args)                                                                    │
│   991                                                                                            │
│                                                                                                  │
│ A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\sd-scripts\train_network.py:798 in train       │
│                                                                                                  │
│   795 │   │   │   │   │                                                                          │
│   796 │   │   │   │   │   loss = loss.mean()  # 平均なのでbatch_sizeで割る必要なし               │
│   797 │   │   │   │   │                                                                          │
│ ❱ 798 │   │   │   │   │   accelerator.backward(loss)                                             │
│   799 │   │   │   │   │   if accelerator.sync_gradients and args.max_grad_norm != 0.0:           │
│   800 │   │   │   │   │   │   params_to_clip = network.get_trainable_params()                    │
│   801 │   │   │   │   │   │   accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)    │
│                                                                                                  │
│ A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\accelerato │
│ r.py:1743 in backward                                                                            │
│                                                                                                  │
│   1740 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1741 │   │   │   return                                                                        │
│   1742 │   │   elif self.scaler is not None:                                                     │
│ ❱ 1743 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   1744 │   │   else:                                                                             │
│   1745 │   │   │   loss.backward(**kwargs)                                                       │
│   1746                                                                                           │
│                                                                                                  │
│ A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\python\lib\site-packages\torch\_tensor.py:487  │
│ in backward                                                                                      │
│                                                                                                  │
│    484 │   │   │   │   create_graph=create_graph,                                                │
│    485 │   │   │   │   inputs=inputs,                                                            │
│    486 │   │   │   )                                                                             │
│ ❱  487 │   │   torch.autograd.backward(                                                          │
│    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    489 │   │   )                                                                                 │
│    490                                                                                           │
│                                                                                                  │
│ A:\_ai\novelai\lora-script-ui\lora-scripts-v1.5.1\python\lib\site-packages\torch\autograd\__init │
│ __.py:200 in backward                                                                            │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
![image](https://github.com/Akegarasu/lora-scripts/assets/50487613/2c2d0d76-d38b-4a31-8554-85add7c5fa79)

![image](https://github.com/Akegarasu/lora-scripts/assets/50487613/4f063e03-fe5a-4fc1-8d43-00f73c94cb51)

![image](https://github.com/Akegarasu/lora-scripts/assets/50487613/1fc22836-dae8-4767-a022-820aaa4af0b3)

**Comment by plhys** [comment]
同样问题，
