### ISSUE TITLE
求救，更新到了最新的安装包，问题依然没有解决，求大佬指点

### ISSUE THREAD

**Issue by andybb6779** [Akegarasu/lora-scripts#219]
![1](https://github.com/Akegarasu/lora-scripts/assets/143988892/3920614e-4870-44e3-82ee-739128ec7c12)
![2](https://github.com/Akegarasu/lora-scripts/assets/143988892/94695a31-549c-4949-978e-30aac1453546)
![3](https://github.com/Akegarasu/lora-scripts/assets/143988892/0418f1f4-bdc9-47fa-8561-1675e7226616)
![4](https://github.com/Akegarasu/lora-scripts/assets/143988892/16654f2a-5597-44ee-9b2e-a51fce81b3e7)

**Comment by wakening** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/32231663/bd130e33-ab64-4766-97da-976a333179e0)
可能是全角字符问题，图片名字用全英文试试

**Comment by dzc2009** [comment]
source 进入虚拟环境再执行试试

**Comment by Akegarasu** [comment]
try delete txt file and use tagger to make caption file again
