### ISSUE TITLE
运行库缺失

### ISSUE THREAD

**Issue by MrZhongzq** [Akegarasu/lora-scripts#22]
python提示缺失triton并且pip安装不了,不论是系统的pip还是venv下的pip.
<img width="819" alt="截屏2023-03-03 12 31 33" src="https://user-images.githubusercontent.com/108169409/222631984-a5f1a2ab-4077-49e7-829f-4d12794c1aa9.png">

并且建议升级一下包里的torch,据说1.13.1和xformers0.0.16提升很大

**Comment by Akegarasu** [comment]
尝试使用--pre安装triton.
升级torch差距不大

**Comment by MrZhongzq** [comment]
PS G:\lora-scripts\venv\Scripts> .\pip.exe install --pre triton
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS G:\lora-scripts\venv\Scripts>

**Comment by MrZhongzq** [comment]
用 --pre也不行,好像是库里没这包

**Comment by Akegarasu** [comment]
检查一下你的pip源


________________________________

**Comment by fungyua** [comment]
看了一下，triton只支持Linux，为什么在Windows上回调用它

**Comment by Akegarasu** [comment]
没注意他是windows，确实windows上不需要安。
重安一下xformers

**Comment by UnsleepingCat** [comment]
> 没注意他是windows，确实windows上不需要安。 重安一下xformers

大佬一直会出现这个情况
![image](https://user-images.githubusercontent.com/130221480/230734404-c57c8534-067f-42b8-b8e4-50081bbf1a2b.png)
虽说对速度可能没有什么影响，但是看着不是很舒服，请问有没有什么解决办法呢？
