### ISSUE TITLE
libcudart.so not found

### ISSUE THREAD

**Issue by dragonjay-lyj** [Akegarasu/lora-scripts#225]
The following directories listed in your path were found to be non-existent: {WindowsPath('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAlho5niLC50W5R2o9waczSgQAAAACAAAAAAAQZgAAAAEAACAAAABuPbdlYhIk+bSOcI+M50oU7RzkQjKsWOuQwH9RnDbGrAAAAAAOgAAAAAIAACAAAABeCJPYyA0TM0HXlN+g/mjlUuoFP2KyjQaAGwUKUKczAGAAAAB9SsgRYoD22MAL+1z6F41vQj0ub8ost6ukp+JbXubUpj+YIYgUyLU0zoWHmSkTwvnklNAnfEc11MUDW091L6TtdkThrexzsjP+yPCvpUErK0dDlGA/fKBZhrIOgSKfTK1AAAAAeUVM6DGdBo5krtgjB2n1T0AJTUshhEgaQZIOJAmuEZW1M8UTFdrv7jW0JGAg6UDyfIbzHAyt2Fc604PL8R2QLw==')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\lora-scripts\venv\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

怎么办，电脑上装了cuda

**Comment by Akegarasu** [comment]
upgrade to the latest version

**Comment by yyyhainan** [comment]
请问是更新什么呀，用命令行如何实现
