### ISSUE TITLE
SDXL训练报错

### ISSUE THREAD

**Issue by yyx0701** [Akegarasu/lora-scripts#226]
![111](https://github.com/Akegarasu/lora-scripts/assets/46587505/fdd471e4-e707-4c2c-8bb6-729741434383)
图片文件也能正常打开浏览，但是训练报这个错误，不知道这个图片文件出了什么问题？？
有哪位大佬解决这个问题吗？

**Comment by yyx0701** [comment]
就是部分图片有这种问题，很操蛋

**Comment by yyx0701** [comment]
我勒个去，打开bf16就没问题，真搞笑。

**Comment by Akegarasu** [comment]
use https://huggingface.co/madebyollin/sdxl-vae-fp16-fix
