### ISSUE TITLE
切换不了优化器，坐等大佬修复

### ISSUE THREAD

**Issue by ZlX2000** [Akegarasu/lora-scripts#230]
![QQ截图20230910232002](https://github.com/Akegarasu/lora-scripts/assets/72849760/70768eb0-e19e-4580-9b63-96fa8740cca6)

**Comment by ZlX2000** [comment]
目前好像只有选DAdaptation优化器时才会出现选不到的问题，不论练什么、多少张图，d*lr都是同一值

**Comment by ZlX2000** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/72849760/4ea839c1-de2c-420b-8974-99049b242d5a)
每次优化器设置恢复默认值后再选DAdaptation右边还是AdamW8bit，选其他优化器正常

**Comment by Akegarasu** [comment]
已确认bug，暂时不要用恢复默认值这个按钮

**Comment by shigma** [comment]
我的锅，应该已经修了。

**Comment by ZlX2000** [comment]
目前重置全部参数后，再次填写，发现选择DAdaptation优化器不论练多少张图，d*lr都是定值，我测试70多张图或3张图都是1e-6
![QQ截图20230925220314](https://github.com/Akegarasu/lora-scripts/assets/72849760/10a145a0-2370-4f93-9fa8-4be7bc0c205a)
