### ISSUE TITLE
更新1.60后过去保存的参数都消失了

### ISSUE THREAD

**Issue by RexLeeGrey** [Akegarasu/lora-scripts#235]
如题
![image](https://github.com/Akegarasu/lora-scripts/assets/125941057/257f671f-2c0b-40e1-81a6-8fc6ab3ee4cf)

**Comment by Akegarasu** [comment]
检查是否清空浏览器缓存，参数都是保存在浏览器内。新版本目前读取tmol、支持导入导出了，可以自己慢慢恢复
