### ISSUE TITLE
更新后同参数的训练效果和之前不同了

### ISSUE THREAD

**Issue by RexLeeGrey** [Akegarasu/lora-scripts#236]
之前用Dadaptation优化器，constant调度器训练出来的lr/d*lr值分别除以3和8，就能获得两个数值，将前一个数值填写在总学习率和U-net学习率上，将后一个数值填写在text-encoding学习率上，使用Lion和cosine with restarts就能获得使用Dadaotation优化器相同的loss曲线，但是新版loss曲线差的很远。且训练所需时长也相差很远。
旧版：
![image](https://github.com/Akegarasu/lora-scripts/assets/125941057/8845a385-e151-425d-b4d4-f6486b4ae876)
新版：
![image](https://github.com/Akegarasu/lora-scripts/assets/125941057/aca43130-054a-49cf-84b3-498f55ea96c0)

**Comment by hopeyan476868** [comment]
遇到同样的问题，而且训练出图一直有问题

**Comment by Akegarasu** [comment]
无法复现区别
