### ISSUE TITLE
你好大佬，遇到这个问题了，咋解决呀。

### ISSUE THREAD

**Issue by babyta** [Akegarasu/lora-scripts#238]
![image](https://github.com/Akegarasu/lora-scripts/assets/37787795/5c34e65d-12f9-4a15-b079-c12d3357ff96)

**Comment by Akegarasu** [comment]
网络问题

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by babyta** [comment]
你好，这个有什么解决方法吗？

**Comment by babyta** [comment]
解决了，sd-scripts\library\openai\openaiclip-vit-large-patch14  下载到本地，改下代码里面路径
