### ISSUE TITLE
多GPU训练失败,提示没有安装NVIDIA NCCL,可是windows好像安装不了NCCL

### ISSUE THREAD

**Issue by AlexanderDash** [Akegarasu/lora-scripts#239]
![QQ浏览器截图20230921093404](https://github.com/Akegarasu/lora-scripts/assets/134115886/ae75e204-bfbc-4a5f-8845-66093fa24f5c)

**Comment by AlexanderDash** [comment]
用的是两张2080ti

**Comment by Akegarasu** [comment]
尝试自己重新部署
