### ISSUE TITLE
更新1.5.0后，即使同样的数据集和参数，训练后的模型依然是色块

### ISSUE THREAD

**Issue by hopeyan476868** [Akegarasu/lora-scripts#241]
尝试1.5底膜和sdxl底膜训练，训练过程没问题，loss下降也很好，就是训练的模型文生图是色块。
！
<img width="347" alt="企业微信截图_cc3bd46b-a6f2-4e27-846a-15bc66890a98" src="https://github.com/Akegarasu/lora-scripts/assets/124242176/e5ea6b2c-9152-419e-beaa-ebd98351569e">

**Comment by Akegarasu** [comment]
无法复现区别
