### ISSUE TITLE
did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] 

### ISSUE THREAD

**Issue by yyyhainan** [Akegarasu/lora-scripts#243]
```
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/lib/python3.8/dist-packages/cv2/../../lib64'), PosixPath('/usr/local/nvidia/lib64')}
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
```
但是我
```
root@ai:/workspace/lora-scripts# ls /usr/local/cuda/lib64/libcudart.so*
/usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libcudart.so.12  /usr/local/cuda/lib64/libcudart.so.12.2.53
```
请问怎么解决？
附：本机cuda是12.2，pytorch装了最新的11.8

**Comment by Akegarasu** [comment]
信息不足，无法判断。疑似cuda环境没装好

**Comment by wangrendong-yition** [comment]
same issue, seems like CUDA version and bitsandbytes version conflict
OS: ubuntu20.04, CUDA version: 12.1,
run bash `train.sh` or `python  -m bitsandbytes`, following bug:

False

===================================BUG REPORT===================================
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/rdwang/anaconda3/envs/lora_py3.10 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: :/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('10809'), PosixPath('http'), PosixPath('//127.0.0.1')}
The following directories listed in your path were found to be non-existent: {PosixPath('10809'), PosixPath('http'), PosixPath('//127.0.0.1')}
The following directories listed in your path were found to be non-existent: {PosixPath('10809'), PosixPath('http'), PosixPath('//127.0.0.1')}
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

currently in install.bash, there are: torch==2.0.1+cu118  torchvision==0.15.2+cu118  xformers==0.0.21
just `pip uninstall` above three package and manually install latest version will solve this problem, may need torch version >= 2.1.0

issue里跟bitsandbytes有关的问题都是类似的
考虑下更新下install.bash适配下12+版本的CUDA? @Akegarasu

**Comment by York-RDWang** [comment]
same issue, seems like CUDA version and bitsandbytes version conflict
OS: ubuntu20.04, CUDA version: 12.1,
run bash `train.sh` or `python -m bitsandbytes`, following bug:

False

===================================BUG REPORT===================================
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


warn(msg)
================================================================================
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/rdwang/anaconda3/envs/lora_py3.10 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: :/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/rdwang/anaconda3/envs/lora_py3.10/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

currently in install.bash, there are: torch==2.0.1+cu118 torchvision==0.15.2+cu118 xformers==0.0.21
just `pip uninstall` above three package and manually install latest version will solve this problem, may need torch version >= 2.1.0

issue里跟bitsandbytes有关的问题似乎都是类似的 @Akegarasu

**Comment by Ginger123319** [comment]
> ```
> The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/lib/python3.8/dist-packages/cv2/../../lib64'), PosixPath('/usr/local/nvidia/lib64')}
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> libcusparse.so.11: cannot open shared object file: No such file or directory
> CUDA SETUP: Something unexpected happened. Please compile from source:
> ```
> 
> 但是我
> 
> ```
> root@ai:/workspace/lora-scripts# ls /usr/local/cuda/lib64/libcudart.so*
> /usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libcudart.so.12  /usr/local/cuda/lib64/libcudart.so.12.2.53
> ```
> 
> 请问怎么解决？ 附：本机cuda是12.2，pytorch装了最新的11.8

在linux环境运行碰到了一样的问题，修改bitsandbytes包的版本可以解决，pip install bitsandbytes==0.35.0；可以试一下！

**Comment by zhuochunli** [comment]
> > ```
> > The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/lib/python3.8/dist-packages/cv2/../../lib64'), PosixPath('/usr/local/nvidia/lib64')}
> > /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
> >   warn(msg)
> > CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> > DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
> > CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
> > CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> > CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> > libcusparse.so.11: cannot open shared object file: No such file or directory
> > CUDA SETUP: Something unexpected happened. Please compile from source:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是我
> > ```
> > root@ai:/workspace/lora-scripts# ls /usr/local/cuda/lib64/libcudart.so*
> > /usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libcudart.so.12  /usr/local/cuda/lib64/libcudart.so.12.2.53
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问怎么解决？ 附：本机cuda是12.2，pytorch装了最新的11.8
> 
> 在linux环境运行碰到了一样的问题，修改bitsandbytes包的版本可以解决，pip install bitsandbytes==0.35.0；可以试一下！

谢谢，我从0.41.0降到0.35.0就可以了！之前一直报这个错
