### ISSUE TITLE
你好，读取图片错误

### ISSUE THREAD

**Issue by babyta** [Akegarasu/lora-scripts#246]
![image](https://github.com/Akegarasu/lora-scripts/assets/37787795/634784b3-953c-4468-8a00-21f76f729080)
![image](https://github.com/Akegarasu/lora-scripts/assets/37787795/9ef4247a-635f-40c9-9c59-e0f20b2c4151)
zhesh这是我的配置

**Comment by qdhonker** [comment]
$train_data_dir="./train/"就可以了，out不要，然后out文件夹改成6_out这种应该就可以跑起来
