### ISSUE TITLE
训练失败，提示returned non-zero exit status 1

### ISSUE THREAD

**Issue by kian996** [Akegarasu/lora-scripts#247]
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\AI\\AIsoftware\\lora-scripts-gui\\python\\python.exe', './sd-scripts/sdxl_train_network.py', '--config_file', 'E:\\AI\\AIsoftware\\lora-scripts-gui\\config\\autosave\\20230925-152417.toml']' returned non-zero exit status 1.

**Comment by yuchaolong** [comment]
好像没看到是怎么解决的
