### ISSUE TITLE
各大云平台SDXL微调 加载到UNet2DConditionModel 经常出错

### ISSUE THREAD

**Issue by Pevernow** [Akegarasu/lora-scripts#252]
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel 
已检查模型sha256，确认下载模型完整，本机windows可以正常加载。
已尝试不同的模型，分别是HelloWorld和XXMix，均存在此bug。
已按照README安装环境。
在Colab,阿里云PAI，ModelscopeNotebook，AutoDL均尝试过，仅AutoDL成功微调。
Python版本在3.8和3.10都试过，都不行。
观察到运行您的WEBUI推理包时，在从SD模型切换到SDXL模型时，偶尔也会加载失败，出现相同错误，猜测是模型格式识别不出SDXL导致的？
请大佬赐教。
[20230929-073943.toml.txt](https://github.com/Akegarasu/lora-scripts/files/12775795/20230929-073943.toml.txt)

**Comment by Pevernow** [comment]
@Akegarasu 大佬你可把我害惨了。
国庆为了SDXL的训练我已经花了不下十几个小时的人工了.......还有一堆的经费。
因为在云服务器上训练，一般我就没想开GUI（除了AutoDL可以直接开很方便）
我本地已经生成好了toml配置了，看仓库里有个train_by_toml，我改了改参数就直接用了。
没想到这个只能调用train_networks......压根不能训练SDXL，SDXL是用sdxl_train_networks。
要不是我今天看了kohya的仓库源码和你的源码，真的想不到会在这种地方出错......
呜呜呜~~

**Comment by Pevernow** [comment]
赶紧改一下train_by_toml，不然就单独写一个sdxl_train_by_toml，不要在让其他人掉进我掉过的坑了。

**Comment by Akegarasu** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/36563862/cd81069e-9925-4519-b679-832eb50271bc)

**Comment by Pevernow** [comment]
> ![image](https://user-images.githubusercontent.com/36563862/271833548-cd81069e-9925-4519-b679-832eb50271bc.png)

这个我看到了，这是webui上的。我在本地用webui训练的好好的。然后拿同一个配置文件用linux纯命令行训练train_by_toml.py就不行了。
因为命令行版本压根不识别sdxl还是sd，通通都当sd训练了
