### ISSUE TITLE
电脑上有两张独立显卡,如何自由选择?

### ISSUE THREAD

**Issue by AlexanderDash** [Akegarasu/lora-scripts#253]

**Comment by Akegarasu** [comment]
set envrionment var `CUDA_VISIBLE_DEVICES`

**Comment by babyta** [comment]
你好，在train_network.py文件里设置吗

**Comment by babyta** [comment]
> 你好，在train_network.py文件里设置吗

测了下，可以的  import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'  加在train_network.py
