### ISSUE TITLE
在主分支cc9b8ac和之后的主分支对比，使用DAdaptLion时loss函数不同，并且后者训练出的档案图像似乎损坏

### ISSUE THREAD

**Issue by AIEXAAA** [Akegarasu/lora-scripts#256]
在主分支cc9b8ac以及之后的主分支，使用DAdaptLion时，你只需跑四个训练

循环就会发现他们的loss函数不同，并且在主分支cc9b8ac之后的分支有问题。

这个问题并非您的程序有问题，而在于文件夹内sd-scripts引用的程序代码有

问题。

如果您在支cc9b8ac之后的分支把sd-script\library\model_util.py中的1047行:

        # logging.set_verbosity_error()  # don't show annoying warning
        # text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
        # logging.set_verbosity_warning()
        # print(f"config: {text_model.config}")
           cfg = CLIPTextConfig(
               vocab_size=49408,
               hidden_size=768,
               intermediate_size=3072,
               num_hidden_layers=12,
               num_attention_heads=12,
               max_position_embeddings=77,
               hidden_act="quick_gelu",
               layer_norm_eps=1e-05,
               dropout=0.0,
               attention_dropout=0.0,
               initializer_range=0.02,
               initializer_factor=1.0,
               pad_token_id=1,
               bos_token_id=0,
               eos_token_id=2,
               model_type="clip_text_model",
               projection_dim=768,
               torch_dtype="float32",
           )
           text_model = CLIPTextModel._from_config(cfg)

改为

    logging.set_verbosity_error()  # don't show annoying warning
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to(device)
    logging.set_verbosity_warning()
    print(f"config: {text_model.config}")
    # cfg = CLIPTextConfig(
    #     vocab_size=49408,
    #     hidden_size=768,
    #     intermediate_size=3072,
    #     num_hidden_layers=12,
    #     num_attention_heads=12,
    #     max_position_embeddings=77,
    #     hidden_act="quick_gelu",
    #     layer_norm_eps=1e-05,
    #     dropout=0.0,
    #     attention_dropout=0.0,
    #     initializer_range=0.02,
    #     initializer_factor=1.0,
    #     pad_token_id=1,
    #     bos_token_id=0,
    #     eos_token_id=2,
    #     model_type="clip_text_model",
    #     projection_dim=768,
    #     torch_dtype="float32",
    # )
    # text_model = CLIPTextModel._from_config(cfg)

并且将以下两行程序删除
sd-script\train_network.py中的228行

         if torch.__version__ >= "2.0.0":  # PyTorch 2.0.0 以上対応のxformersなら以下が使える
             vae.set_use_memory_efficient_attention_xformers(args.xformers)

则训练出来的loss函数会和主分支cc9b8ac相同。

其中sd-script\library\model_util.py中的1047行影响起始loss函数
sd-script\train_network.py中的228行影响训练过程中的loss函数

**Comment by Akegarasu** [comment]
related commits https://github.com/kohya-ss/sd-scripts/commit/449ad7502cb0f36cd8b94b2c7d98ec204af234a9
please submit issue in [sd-scripts](https://github.com/kohya-ss/sd-scripts/issues).

**Comment by AIEXAAA** [comment]
> 相關提交 [kohya-ss/sd-scripts@449ad75](https://github.com/kohya-ss/sd-scripts/commit/449ad7502cb0f36cd8b94b2c7d98ec204af234a9) 請在 [SD 腳本](https://github.com/kohya-ss/sd-scripts/issues)中提交問題。

您是对的。我只是看到#236提到这问题，然后您说无法复现，因此特别提出来说明此现象真的存在，如果其他人想要回到先前的loss函数，可以照此修改。
当然也是希望如果作者您有解决方法，例如另外做一个开关使用旧有的训练程序代码等……。
