### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by jokerJ78** [Akegarasu/lora-scripts#259]
"Unsupported cuda version:11.0" was reported during install.bash processing step.

<img width="341" alt="installation issue" src="https://github.com/Akegarasu/lora-scripts/assets/42563859/3631a56c-0888-452e-9721-3a1652ef49dd">

**Comment by jokerJ78** [comment]
Got it. I need to update my Cuda version upper than 11.8
![image](https://github.com/Akegarasu/lora-scripts/assets/42563859/541b9749-3c48-4504-8280-5585a9f31ade)

**Comment by jokerJ78** [comment]
<img width="746" alt="cuda_version" src="https://github.com/Akegarasu/lora-scripts/assets/42563859/0e5f9aeb-d521-4a60-b11d-5c2b345a0f44">

**Comment by Akegarasu** [comment]
This is the correct approach. Generally, cu113 is the minimum supported version, but this repo has chosen cu116 as the minimum.
