### ISSUE TITLE
其他依赖安装失败。报错：ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by li258w** [Akegarasu/lora-scripts#26]
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
Collecting torch==1.12.1+cu116
  Downloading https://mirror.sjtu.edu.cn/pytorch-wheels/cu116/torch-1.12.1%2Bcu116-cp310-cp310-win_amd64.whl (2388.4 MB)
     ---------------------------------------- 2.4/2.4 GB 34.4 MB/s eta 0:00:00
Collecting torchvision==0.13.1+cu116
  Downloading https://mirror.sjtu.edu.cn/pytorch-wheels/cu116/torchvision-0.13.1%2Bcu116-cp310-cp310-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 9.6 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting numpy
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/fa/df/53e8c0c8ccecf360b827a3d2b1b6060644c635c3149a9d6415a6fe4ccf44/numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
     ---------------------------------------- 14.8/14.8 MB 65.1 MB/s eta 0:00:00
Collecting requests
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.8/62.8 kB ? eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/5e/7c/293136a5171800001be33c21a51daaca68fae954b543e2c015a6bb81a716/Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 154.1 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.5/61.5 kB ? eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl (155 kB)
     ---------------------------------------- 155.3/155.3 kB ? eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/98/f4/5ca33ee1e0b3412cbd13eae230321a9fe819acf1a99ad6482420fb97cc6b/charset_normalizer-3.0.1-cp310-cp310-win_amd64.whl (96 kB)
     ---------------------------------------- 96.5/96.5 kB ? eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ---------------------------------------- 140.6/140.6 kB ? eta 0:00:00
Installing collected packages: charset-normalizer, urllib3, typing-extensions, pillow, numpy, idna, certifi, torch, requests, torchvision
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.12.1+cu116 torchvision-0.13.1+cu116 typing-extensions-4.5.0 urllib3-1.26.14
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
其他依赖安装失败。
安装失败。

**Comment by Akegarasu** [comment]
#7
