### ISSUE TITLE
GUI错误

### ISSUE THREAD

**Issue by nasa459** [Akegarasu/lora-scripts#260]
**问题**
在页面中更改任意数值后，右侧参数预览不显示，点击“开始训练”按钮无反应

**环境**
使用百度网盘下载的一键启动包，使用强制更新脚本更新至最新

**Comment by Akegarasu** [comment]
请提供详细报错（f12->console）

**Comment by nasa459** [comment]
解决了，浏览器开了UA插件，将UA改回edge就正常了
