### ISSUE TITLE
num regulation image: 0

### ISSUE THREAD

**Issue by ZaPravdu** [Akegarasu/lora-scripts#269]
我确定了训练集的路径，但是脚本告诉我正则化图片数为0。有人遇到过这种情况吗？
I have specified the path of regulation set, but the script just tells me num of regulation image: 0. Have ever been such situation?

**Comment by Akegarasu** [comment]
regulation set also needs put image file follow the path rule like this:
```
- foo
 -- 6_bar 
```
then, reg path is foo.
