### ISSUE TITLE
install-cn.ps1使用powershell运行就闪退，是啥原因啊？

### ISSUE THREAD

**Issue by llinlluo** [Akegarasu/lora-scripts#274]
install-cn.ps1使用powershell运行就闪退，是啥原因啊？

**Comment by LinanqiaoMing** [comment]
> install-cn.ps1使用powershell运行就闪退，是啥原因啊？

试试用Get-ExecutionPolicy命令查看你的执行策略，如果是Restricted，就表示你不能运行任何脚本。你可以用Set-ExecutionPolicy命令来修改你的执行策略，比如Set-ExecutionPolicy RemoteSigned，这样你就可以运行本地的或者签名的远程脚本了。

**Comment by llinlluo** [comment]
Hi,
Thank you for writing back, the problem has been solved, have a nice day!

Cecile
________________________________
