### ISSUE TITLE
lokr训练中需要定义factor值，但是本UI界面没有给出相关设置选项

### ISSUE THREAD

**Issue by UnsleepingCat** [Akegarasu/lora-scripts#283]
如题

**Comment by Akegarasu** [comment]
fixed

**Comment by UnsleepingCat** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/130221480/0726ac15-fd08-4a3d-82b1-e9f087f877a8)
大佬。依旧是没有选项弹出的。已经使用国内强制更新过了

**Comment by UnsleepingCat** [comment]
使用国外源就能更新到。国内没有更新到。此时此刻。国内源可能需要明天才能更新了。
