### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by huangjianyi0701** [Akegarasu/lora-scripts#284]
subprocess.CalledProcessError: Command '['D:\\lora\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/moyou_fp16.safetensors', '--train_data_dir=./train/beach', '--output_dir=./output', '--logging_dir=./logs', '--log_prefix=beach', '--resolution=768,768', '--network_module=networks.lora', '--max_train_epochs=150', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=beach', '--train_batch_size=1', '--save_every_n_epochs=30', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by huangjianyi0701** [comment]
已解决

**Comment by LinanqiaoMing** [comment]
请问怎么解决的？
