### ISSUE TITLE
UI里是否能在专业模式中添加optimizer_args = [ "weight_decay=0.1",

### ISSUE THREAD

**Issue by UnsleepingCat** [Akegarasu/lora-scripts#285]
![image](https://github.com/Akegarasu/lora-scripts/assets/130221480/e4771a35-36cc-42eb-bf67-9ad223ab1689)

如题。谢谢！

**Comment by Akegarasu** [comment]
![Uploading image.png…]()

**Comment by UnsleepingCat** [comment]
好的谢谢！
