### ISSUE TITLE
刚好Cuda 11.7不支持么,why?

### ISSUE THREAD

**Issue by qianlnk** [Akegarasu/lora-scripts#287]
bash install.bash 
Creating python venv...
active venv
Installing torch & xformers...
Cuda Version:11.7
Unsupported cuda version:11.7

![image](https://github.com/Akegarasu/lora-scripts/assets/9543166/3948f670-3d0a-4eb7-836f-b15fd6a929e7)

**Comment by Akegarasu** [comment]
bug
