### ISSUE TITLE
有没有对应的docker镜像

### ISSUE THREAD

**Issue by qianlnk** [Akegarasu/lora-scripts#288]
单单bash install.bash 这一步就卡死好多好汉😂

**Comment by Akegarasu** [comment]
cu118以后的xformers都不需要编译安装 install.bash没有难度

**Comment by Akegarasu** [comment]
https://github.com/Akegarasu/lora-scripts/blob/main/Dockerfile

**Comment by geekidentity** [comment]
https://hub.docker.com/r/xxlab/lora-scripts
做了一个镜像

**Comment by inewlife** [comment]
> https://github.com/Akegarasu/lora-scripts/blob/main/Dockerfile

这个有bug，提示xformers wasn't build with cuda support
