### ISSUE TITLE
tensorboard与标签编辑器404，控制台未报错

### ISSUE THREAD

**Issue by ZlX2000** [Akegarasu/lora-scripts#289]
![image](https://github.com/Akegarasu/lora-scripts/assets/72849760/09b4ea9f-058f-4637-8168-c3c5b827e986)
![image](https://github.com/Akegarasu/lora-scripts/assets/72849760/f20f91a2-91a9-44a1-b076-75d0adc2e31e)
情况如图，A强制更新-国内加速.bat已更新到最新版本
![image](https://github.com/Akegarasu/lora-scripts/assets/72849760/baba0ed6-a9b0-4179-aa45-36d910486971)

**Comment by Akegarasu** [comment]
无法复现。尝试shift+f5强制刷新网页

**Comment by ZlX2000** [comment]
好像是梯子的问题，关了VPN就好了
