### ISSUE TITLE
如何平衡速度和显存使用？

### ISSUE THREAD

**Issue by NaughtDZ** [Akegarasu/lora-scripts#294]
训练SDXL用的Lora，如果我不开启梯度检查点，16G显存必然会爆炸。但是开了的话，速度奇慢无比不说，显存占用只有11G反而浪费了。有啥优化设置能平衡一下速度和占用嘛？希望各位大佬能提点建议。

**Comment by tangflash** [comment]
是的，太慢了，训练sdxl没法用
