### ISSUE TITLE
标签编辑器404 UI错误

### ISSUE THREAD

**Issue by aDropp** [Akegarasu/lora-scripts#297]
![1](https://github.com/Akegarasu/lora-scripts/assets/80192879/de196be9-a260-4b7e-84aa-49d8f4227fdc)
点击 `Take me home` 之后会出现下图的UI错误
![2](https://github.com/Akegarasu/lora-scripts/assets/80192879/c2693bcb-b05b-48cb-8871-297e67b5dc08)

**Comment by Akegarasu** [comment]
无法复现。请提供详细情况

**Comment by aDropp** [comment]
这个可以吗？

https://github.com/Akegarasu/lora-scripts/assets/80192879/59a45134-1b44-4aa7-b448-e103b774c995

**Comment by Akegarasu** [comment]
尝试清空浏览器缓存

**Comment by 1803233552** [comment]
同样的问题，在强制更新到最新的main后，点击TensorBoard和标签编辑器出现404

**Comment by 1803233552** [comment]
> 同样的问题，在强制更新到最新的main后，点击TensorBoard和标签编辑器出现404

清空浏览器缓存无效

**Comment by 1803233552** [comment]
补充一点，这个TensorBoard加载时间比较长，一开始让我以为出问题了。建议加点提示。
![image](https://github.com/Akegarasu/lora-scripts/assets/71918224/9502fcd9-5ea4-4dbf-9d58-98798b52ffe7)
