### ISSUE TITLE
標籤編輯器載入圖像時連線超時

### ISSUE THREAD

**Issue by YuiZhushi** [Akegarasu/lora-scripts#298]
![image](https://github.com/Akegarasu/lora-scripts/assets/125752787/31f1b83a-1617-4f9c-8ddc-7f376216697e)
![image](https://github.com/Akegarasu/lora-scripts/assets/125752787/84da7eac-d7a9-485c-a032-ae42c29c43dd)
![image](https://github.com/Akegarasu/lora-scripts/assets/125752787/a5b4680c-4c1f-4b5b-9771-b6aafd1724b4)

資料集有975張圖片與975個txt檔
Windows系統、Edge瀏覽器、網路環境在國外

**Comment by Akegarasu** [comment]
已修复 更新测试

**Comment by YuiZhushi** [comment]
更新後可以正常使用了，感謝修復
