### ISSUE TITLE
sdxl-finetune 选择了多gpu，但是只有一个GPU在工作的问题

### ISSUE THREAD

**Issue by ORGRUI** [Akegarasu/lora-scripts#301]
在 sdxl-finetune 训练的时候选择了多GPU训练：
![image](https://github.com/Akegarasu/lora-scripts/assets/26873136/212696cd-2207-4fc7-addc-25ac980a4f48)

但是实际只有一个GPU在工作
![image](https://github.com/Akegarasu/lora-scripts/assets/26873136/2315de8b-dd51-4646-96b3-6da39426a319)

没找到在哪里可以设置用于训练的GPU的设备号如（0,1,2,3）这样。

希望大佬有空的话可以回复一下，谢谢～

**Comment by onijack888** [comment]
我的双3090也是，点击多显卡，开始训练LORA就会报错

**Comment by Akegarasu** [comment]
> 秋叶佬一直没有解决`./mikazuki/process.py`里面的问题。 大佬的想法我不懂，也不知道为啥不debug_**_（好久了，大概有好几个版本了。）_**_，没办法，我这边目前是WSL2环境下开NCCL用两块4080跑的，大致经验如下 看一下参考链接： #120
> 
之前忘记了 改了
