### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by Blanzie** [Akegarasu/lora-scripts#31]
没有国内手机，夸克网盘那个下载不了
如果运行install cn会安装依赖失败
运行install会标红

cp : 找不到路径“I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\sd-scripts\bitsandbytes_windows”，因为该路径不
存在。
所在位置 I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\install.ps1:16 字符: 1
+ cp .\bitsandbytes_windows\*.dll ..\venv\Lib\site-packages\bitsandbyte ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (I:\stable-diffu...ndbytes_windows:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

cp : 找不到路径“I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\sd-scripts\bitsandbytes_windows\cextension.py”
，因为该路径不存在。
所在位置 I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\install.ps1:17 字符: 1
+ cp .\bitsandbytes_windows\cextension.py ..\venv\Lib\site-packages\bit ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (I:\stable-diffu...s\cextension.py:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

cp : 找不到路径“I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\sd-scripts\bitsandbytes_windows\main.py”，因为
该路径不存在。
所在位置 I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\install.ps1:18 字符: 1
+ cp .\bitsandbytes_windows\main.py ..\venv\Lib\site-packages\bitsandby ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (I:\stable-diffu...windows\main.py:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

但是会安装成功，在这样的情况下运行train会

accelerate : 无法将“accelerate”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请
确保路径正确，然后再试一次。
所在位置 I:\stable-diffusion-webui_23-02-17\lora-scripts-0.2.0\train.ps1:95 字符: 1
+ accelerate launch --num_cpu_threads_per_process=8 "./sd-scripts/train ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

查了一下，Set-ExecutionPolicy -ExecutionPolicy RemoteSigned我也输入了，第二次有确认

**Comment by Blanzie** [comment]
git也装过，git bash here也点了

**Comment by Akegarasu** [comment]
duplicated #2
