### ISSUE TITLE
 使用SDXL训练lora时出现这个问题

### ISSUE THREAD

**Issue by zhihao93li** [Akegarasu/lora-scripts#310]
size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.norm1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([1280]).  使用SDXL训练lora时出现这个问题

**Comment by lifu834** [comment]
Adjust the model_train_type to SDXL_lora
