### ISSUE TITLE
标签器无法工作，huggingface无法访问

### ISSUE THREAD

**Issue by zengziru** [Akegarasu/lora-scripts#316]

**Comment by zengziru** [comment]
提交Tagger任务后，抱这样的错：
![截屏2023-12-25 18 53 56](https://github.com/Akegarasu/lora-scripts/assets/64313978/70f16561-20fa-44e8-bbef-6def91d05093)
我连了VPN，本地可以访问huggingface

**Comment by Akegarasu** [comment]
网络问题自行解决

**Comment by brian95827** [comment]
> 提交Tagger任务后，抱这样的错： ![截屏2023-12-25 18 53 56](https://private-user-images.githubusercontent.com/64313978/292749892-70f16561-20fa-44e8-bbef-6def91d05093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTAwNTQsIm5iZiI6MTcwOTQ0OTc1NCwicGF0aCI6Ii82NDMxMzk3OC8yOTI3NDk4OTItNzBmMTY1NjEtMjBmYS00NGU4LWJiZWYtNmRlZjkxZDA1MDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlY2JjOWE0MzZiZjUwZjI0NGQ3NWFkNWRmZDlkNGQ5YzcyZjFmZjA3NDExNzU2OThhOWY3ZTUyNDRkYzdjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUW2pXHk5eHd-GZubbJ6bX5Z6QNXvQ2UP-cv9v-Z4ws) 我连了VPN，本地可以访问huggingface

---

解决了吗？我也是同样的问题，开不开vpn都报错，直接上huggingface下载文件到本地都不行，不知道是不是哪个地方配置冲突了

**Comment by brian95827** [comment]
> 提交Tagger任务后，抱这样的错： ![截屏2023-12-25 18 53 56](https://private-user-images.githubusercontent.com/64313978/292749892-70f16561-20fa-44e8-bbef-6def91d05093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTEzMjQsIm5iZiI6MTcwOTQ1MTAyNCwicGF0aCI6Ii82NDMxMzk3OC8yOTI3NDk4OTItNzBmMTY1NjEtMjBmYS00NGU4LWJiZWYtNmRlZjkxZDA1MDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWUxNDY3Y2Q4NTE1NDA3NWU2OGYxMmVkNTlhYWQxZDk2OTRlNTUyMDY3YzcwZDk2OGIzYmQ0YjM5OTZmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHTzsyChRrXnoJBoymiuNORhdqidUsWT1gW7AzwtmZE) 我连了VPN，本地可以访问huggingface

---

本地代理用不了，麻了。同样的配置文件，网页打开huggingface都没问题，用本地代理代码就报错，用路由器代理就能用。明明是同一个vpn，无语。
