### ISSUE TITLE
专家和新手模式都显示ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by Rsir754** [Akegarasu/lora-scripts#319]
新手模式
![错误1](https://github.com/Akegarasu/lora-scripts/assets/46583522/eca31d19-baaf-4c78-91b4-e3d010e8ae02)
专家模式改了训练种类依旧
![错误2](https://github.com/Akegarasu/lora-scripts/assets/46583522/0534510a-2d1d-4cab-9090-7b0b627d8f24)

**Comment by wanjunling168** [comment]
麻烦看看报错，你没装diffusers就装了再看，缺什么补什么，完了还报错再来提issue。
pip这玩意网一烂就装不上包，那就多试几次，总之起码把requirements.txt里的装齐再说

**Comment by Rsir754** [comment]
> 麻烦看看报错，你没装diffusers就装了再看，缺什么补什么，完了还报错再来提issue。 pip这玩意网一烂就装不上包，那就多试几次，总之起码把requirements_win.txt里的装齐再说

多次运行install.ps1 install-cn.ps1均显示已安装，结尾也跳出安装完毕，问题依旧
![错误3](https://github.com/Akegarasu/lora-scripts/assets/46583522/817b6c46-c898-4da1-a3dd-47bd24a32c4b)

**Comment by wanjunling168** [comment]
看看你的环境变量里有没有设什么PYTHONPATH之类的（按道理run_gui.ps1是加载了venv的，所以应该不是加载错python了），感觉是没加载到venv里装的site-packages（这个好像不在venv的activate覆写范围）

**Comment by Rsir754** [comment]
> 看看你的环境变量里有没有设什么PYTHONPATH之类的（按道理run_gui.ps1是加载了venv的，所以应该不是加载错python了），感觉是没加载到venv里装的site-packages（这个好像不在venv的activate覆写范围）

系统变量里没有
![错误4](https://github.com/Akegarasu/lora-scripts/assets/46583522/8267c013-9e72-4e8a-ab06-e59c303e9ec6)
用train.ps1直接跑了一次，结果还是说没有diffusers
![错误5](https://github.com/Akegarasu/lora-scripts/assets/46583522/ce7c617a-1944-40f4-a01a-af2c1fd5a34a)

**Comment by wanjunling168** [comment]
这就很怪了，你试试直接开个python窗口（就是在这个目录下直接 .\venv\Scripts\activate.ps1（假设你用PowerShell），然后python），然后直接import一下diffusers看看是什么情况

**Comment by Akegarasu** [comment]
删了venv重装

**Comment by Rsir754** [comment]
> 删了venv重装

怎么定位删除对应的下载缓存，重下了他直接用原来的缓存结果故障依旧

**Comment by wanjunling168** [comment]
```
$Env:PIP_NO_CACHE_DIR = 1
```
脚本内pip安装已经设置不带缓存，感觉你这个是diffusers[torch]装出的问题

**Comment by Rsir754** [comment]
> ```
> $Env:PIP_NO_CACHE_DIR = 1
> ```
> 
> 脚本内pip安装已经设置不带缓存，感觉你这个是diffusers[torch]装出的问题 可以直接装diffusers，确保先装好torch就行 diffusers[torch] -> diffusers, accelerate, torch

重装python3.12，删了整个lora-scripts后，用v1.8.2重装就没出现这个问题了
