### ISSUE TITLE
What are npz files?

### ISSUE THREAD

**Issue by LuluViBritannia** [Akegarasu/lora-scripts#325]
This is not a bug nor a request, just a question out of curiosity.

Whenever I train using this program, it creates one file per image in the folder, each file being named something like "[imagename].npz". What is this? When I decrypt it with a python code it gives tensors, is this a sort of "translation of the images" for the program to use? If that's so, why is it necessary? I don't recall it happening with kohya.

While I'm it: the program also creates a folder called "5_zkz" and pus the whole database in it. Is there a way to disable that? It's annoying when trying to retrain a LoRA with the same database ^^'.

**Comment by Akegarasu** [comment]
latent cache.
