### ISSUE TITLE
能支持大于1的scale_weight_norm吗？

### ISSUE THREAD

**Issue by silvermoong** [Akegarasu/lora-scripts#327]
在UI里scale_weight_norm只能设置到1。现阶段要使用大于1的值只能train by toml

**Comment by Akegarasu** [comment]
为什么会用到大于1的

**Comment by silvermoong** [comment]
> 为什么会用到大于1的

玄学炼丹会用到大于1
有的时候也会开一个非常大的值用于观测key值的增长
