### ISSUE TITLE
更新後訓練報錯

### ISSUE THREAD

**Issue by yamasoo** [Akegarasu/lora-scripts#330]
更新到最新後訓練報錯

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\lora-scripts\mikazuki\app\application.py", line 54, in add_cache_control_header
    response = await call_next(request)
  File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "E:\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "E:\lora-scripts\mikazuki\app\api.py", line 71, in create_toml_file
    result = process.run_train(toml_file, trainer_file, gpu_ids, suggest_cpu_threads)
  File "E:\lora-scripts\mikazuki\process.py", line 33, in run_train
    if len(gpu_ids) > 1:
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "E:\lora-scripts\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "E:\lora-scripts\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "E:\lora-scripts\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "E:\lora-scripts\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "E:\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "E:\lora-scripts\venv\lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |   File "E:\lora-scripts\venv\lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    |     message = await recv_stream.receive()
    |   File "E:\lora-scripts\venv\lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "E:\lora-scripts\mikazuki\app\application.py", line 54, in add_cache_control_header
    |     response = await call_next(request)
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    |     raise app_exc
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    |     raise exc
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "E:\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "E:\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "E:\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 66, in app
    |     response = await func(request)
    |   File "E:\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    |     raw_response = await run_endpoint_function(
    |   File "E:\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "E:\lora-scripts\mikazuki\app\api.py", line 71, in create_toml_file
    |     result = process.run_train(toml_file, trainer_file, gpu_ids, suggest_cpu_threads)
    |   File "E:\lora-scripts\mikazuki\process.py", line 33, in run_train
    |     if len(gpu_ids) > 1:
    | TypeError: object of type 'NoneType' has no len()
    +------------------------------------

**Comment by yamasoo** [comment]
拉回
b024a22cf11f16a68ec01e027c66dd4fb9a6b501
後正常

**Comment by shaoheming** [comment]
最下边那里选一下显卡就好了。

**Comment by shaoheming** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/4082358/c60e2e66-246f-4add-ae29-21f20a3c3899)

**Comment by Akegarasu** [comment]
完整日志发一下

**Comment by Akegarasu** [comment]
哦 不小心写错了
