### ISSUE TITLE
标签编辑器不能用

### ISSUE THREAD

**Issue by qinchuana** [Akegarasu/lora-scripts#333]
标签编辑器加载一段时间后就就报错了，用sd内部的打标器就没问题

**Comment by qinchuana** [comment]
加载一分多钟就这样了
![QUQJ3I{JHB((YLGXPJ$I2WR](https://github.com/Akegarasu/lora-scripts/assets/104222024/1a572a88-93a0-4e8d-9400-c4ae79cbda80)

**Comment by qinchuana** [comment]
加载一分多钟就这样了，cmd也没有报错，是怎么回事？sd里面加载一会就行了
![QUQJ3I{JHB((YLGXPJ$I2WR](https://github.com/Akegarasu/lora-scripts/assets/104222024/ef09c80d-431d-4fca-860a-b8e4b723e248)

**Comment by Coder8chan** [comment]
我也是这样请问。您文件夹里标签格式是怎样的
