### ISSUE TITLE
Jihulab.com block PIA VPN

### ISSUE THREAD

**Issue by Euchale** [Akegarasu/lora-scripts#335]
![image](https://github.com/Akegarasu/lora-scripts/assets/3716287/d6b1a8fa-1176-4def-a613-28a3aa3cfe8a)

Leaving this here in case somebody else runs into this issue. jihulab prevents users of the VPN Private Internet Access to connect. So turn it off and the installation will work.

**Comment by Akegarasu** [comment]
if you're not in china mainland, please use iinstall.ps1 instead
