### ISSUE TITLE
Dreambooth XL，文本编码器的训练从未工作

### ISSUE THREAD

**Issue by giteeeeee** [Akegarasu/lora-scripts#338]
1.8.3版本，windows环境

Dreambooth-sd_XL训练，设置参数（故意将文本编码器调到0.9）：

![4-01-18 204454](https://github.com/Akegarasu/lora-scripts/assets/89521447/2630858f-af09-48b2-ab50-8e48e2a621bc)

且"stop_text_encoder_training"并未设置

点击训练，开始时显示：

![297036849-3dbc31b0-cc20-484a-893a-0fcd6bc07ca6](https://github.com/Akegarasu/lora-scripts/assets/89521447/11b22c9d-bf52-4e99-9d3c-cce1e74a904c)

文本编码器虽然被设定参数，但似乎并未生效

训练到第100+步时loss也并未返回Nan，正常文本编码器设置到0.9时，训练到第二步loss就会Nan

然后去了sd_XL lora进行训练，设了类似的参数，0.9的文本编码器”正常工作”，第二步时loss即返回Nan

进一步证明Dreambooth-sd_XL的文本编码器训练部分并未工作

……

又去下载了KohyaSS的GUI，设置完相同参数，遇到”train unet: True, text encoder1: False, text encoder2:False“的同样问题

后发现需要在以下栏中手动输入：

![52424](https://github.com/Akegarasu/lora-scripts/assets/89521447/b2507076-11df-4aaa-845d-c7c294858d40)

训练：

![41250](https://github.com/Akegarasu/lora-scripts/assets/89521447/e197d790-599e-4ba2-8c61-18760b845694)

0.9的文本编码器正常工作，训练至第二步loss即返回Nan

……

所以回到秋叶这边，如果用的也是kohya内核，那么应该可以在配置文件手动输入“--train_text_encoder”，或是"train_text_encoder = true"，来开启文本编码器的训练

但遇到https://github.com/Akegarasu/lora-scripts/issues/337

无法导入配置文件，当然这是另一个问题了

所以最好能在gui中直接开启训练文本编码器的选项，但它目前是默认关闭的，导致文本编码器从未被训练

**Comment by zodiacg** [comment]
借地问一句，请问精调的是DreamshaperXL的Lightning或Turbo版本吗？我在精调时发现精调后的LoRA在进行20步生成时才会产生较为清晰的图像。DreamshaperXL lightning页面上指出训练时需要设置正确的采样器和步数，请问这部分如何在秋叶的GUI中设置？
