### ISSUE TITLE
 from mikazuki.utils.devices import check_torch_gpu ModuleNotFoundError: No module named 'mikazuki.utils.devices'; 'mikazuki.utils' is not a package

### ISSUE THREAD

**Issue by 108863258** [Akegarasu/lora-scripts#340]
from mikazuki.utils.devices import check_torch_gpu
ModuleNotFoundError: No module named 'mikazuki.utils.devices'; 'mikazuki.utils' is not a package
![image](https://github.com/Akegarasu/lora-scripts/assets/25278613/37700eba-37e3-4df9-b789-afea4543edeb)

**Comment by Akegarasu** [comment]
无法复现，请提供详细信息

**Comment by Fuller001** [comment]
在lora-scripts\mikazuki\app文件夹下添加一个名称__init__.py的文件即可

**Comment by Fuller001** [comment]
> 从 mikazuki.utils.devices 导入 check_torch_gpu ModuleNotFoundError：没有名为“mikazuki.utils.devices”的模块;“mikazuki.utils”不是一个包 ![图像](https://private-user-images.githubusercontent.com/25278613/298883323-37700eba-37e3-4df9-b789-afea4543edeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTA3OTMsIm5iZiI6MTcwNjk1MDQ5MywicGF0aCI6Ii8yNTI3ODYxMy8yOTg4ODMzMjMtMzc3MDBlYmEtMzdlMy00ZGY5LWI3ODktYWZlYTQ1NDNlZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA4NTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Yzk4MDBjNzQ5MjczZjQ3NGYzZmUzZTUwZDAwMjVjNWRkOTc0ZTc1NDlmNDg4MmYxNzc0YmJjMDQ2M2VmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ObY6-2Efn7JxVZySAGiTmmBcSy6Udyi66xqDWQiU5Go)

在lora-scripts\mikazuki\app文件夹下添加一个名称__init__.py的文件即可
