### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by Chelsie096** [Akegarasu/lora-scripts#344]
File "E:\...\lora\u8bad\u7ec3\u5668\lora-scripts-v1.7.3\python\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 12-14: character maps to <undefined>

**Comment by Akegarasu** [comment]
use ascii path
