### ISSUE TITLE
无法训练

### ISSUE THREAD

**Issue by MontaEllis** [Akegarasu/lora-scripts#348]
左边的参数似乎不能在右边显示，点训练也没反应

![image](https://github.com/Akegarasu/lora-scripts/assets/37856372/e7ce8d1b-f79d-42d8-aec0-36c22bc54dde)

**Comment by Akegarasu** [comment]
查看f12内控制台报错

**Comment by MontaEllis** [comment]
![image](https://github.com/Akegarasu/lora-scripts/assets/37856372/cd38bb9a-1c6a-4882-80a2-11304d927d4d)
是这样的报错，麻烦您看看
