### ISSUE TITLE
How can lora-scripts control the GUI to only be accessible through the internal network? Are there parameters similar to 'share=True' in stable diffusion webui?

### ISSUE THREAD

**Issue by huxian0402** [Akegarasu/lora-scripts#358]
I want to use the GUI interface of lora-scripts on the server for training, but there is a risk of information leakage to the external network. Are there parameters similar to 'share' in stable diffusion webui? Is it possible to control and avoid external network access through 'share=False'? Please help answer this, thank you!  @vinjn @Roland0511 @snakeninny @judgeou @lkwfive

**Comment by Akegarasu** [comment]
it's listen on localhost by default.
