### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by yqndxl** [Akegarasu/lora-scripts#370]
秋叶大神您好，我是mac设备（Intel芯片），在“install.bash”这个步骤遇到了如下报错：

Creating python venv...
active venv
Installing torch & xformers...
install.bash: line 27: nvcc: command not found
Cuda Version:
Unsupported cuda version:

请问下应该如何解决（我是程序小白，看不太懂这些东西……跪求指导）

**Comment by brian95827** [comment]
没装nvcc吧？你这机器是没有显卡吗

**Comment by yqndxl** [comment]
> 没装nvcc吧？你这机器是没有显卡吗

intel的显卡，NVCC装不上去，请问这个是必须的吗，应该怎么办呀T-T

**Comment by brian95827** [comment]
> > 没装nvcc吧？你这机器是没有显卡吗
> 
> intel的显卡，NVCC装不上去，请问这个是必须的吗，应该怎么办呀T-T

那就很麻烦了，你得研究一下怎么[用intel显卡安装torch](https://www.intel.cn/content/www/cn/zh/support/articles/000095437/graphics.html)

装完以后再手动装其他依赖，再试试看能不能用。

---

因为你的电脑不太常规所以：

1. 想办法[用intel显卡安装torch](https://www.intel.cn/content/www/cn/zh/support/articles/000095437/graphics.html)
2. `install.bash`脚本不能用了，要自己手动安装依赖。
3. 安装完后不一定就能用，可能不兼容，如果遇到其他问题可能还需要解决其他问题。
4. 解决了也不一定能用。。

**Comment by Akegarasu** [comment]
不支持使用。

**Comment by yqndxl** [comment]
谢谢两位大神，看来我只能换一台电脑了 T~T
