### ISSUE TITLE
标签编辑器，加载的图片一多就报错

### ISSUE THREAD

**Issue by brian95827** [Akegarasu/lora-scripts#372]
```
100%|██████████| 720/720 [00:07<00:00, 98.07it/s] 
240it [00:10, 22.34it/s]
100%|██████████| 240/240 [00:30<00:00,  7.94it/s]
0it [00:00, ?it/s]
20:14:24-061218 ERROR    Error when proxy data backend -> client: sent 1011    
                         (unexpected error) keepalive ping timeout; no close   
                         frame received                    
```

**Comment by e68862230** [comment]
GUI这块可以延长心跳间隔时间么，感觉每次都是操作时间太长而出现这个错误。。

**Comment by brian95827** [comment]
> GUI这块可以延长心跳间隔时间么，感觉每次都是操作时间太长而出现这个错误。。

反正我用的时候都是二分法，数据集太大加载不了就分一半，一半不行就再分一半。。反正分完以后就好了。。
不会改代码，只能这样了。。

**Comment by brian95827** [comment]
怎么打了无效的标签呢。。o(╥﹏╥)o
大佬呀，也许你的旗舰cpu不会超时，但我们的洋垃圾可是真的会超时的呀。。。
几百张图片没个几十秒甚至一分钟是真的加载不完。。

**Comment by pilaoda** [comment]
https://github.com/Akegarasu/lora-scripts/blob/c1fd925cf90d76f41b27d004ddc726c809092267/mikazuki/app/proxy.py#L87
加个`ping_timeout=None`的设置吧秋总 @Akegarasu 
https://websockets.readthedocs.io/en/stable/topics/timeouts.html#keepalive-in-websockets

**Comment by a442509097** [comment]
> https://github.com/Akegarasu/lora-scripts/blob/c1fd925cf90d76f41b27d004ddc726c809092267/mikazuki/app/proxy.py#L87
> 
> 
> 加个`ping_timeout=None`的设置吧秋总 @Akegarasu
> https://websockets.readthedocs.io/en/stable/topics/timeouts.html#keepalive-in-websockets

感谢, 我的是导入图片就是显示这个, 改成这样后就好了
```
async with websockets.connect(ws_b_uri, ping_timeout=None) as ws_b_client:
```
