### ISSUE TITLE
Unable to select newly added WD Tagger v3

### ISSUE THREAD

**Issue by yamasoo** [Akegarasu/lora-scripts#374]
I've updated to the latest version but the menu still doesn't seem to show up.
![image](https://github.com/Akegarasu/lora-scripts/assets/73381291/371ab25a-2165-4057-a9bf-66b43fe7c5f1)
After updating to the latest version, there is still no way to select the newly added taggers.

Preceded by
https://github.com/Akegarasu/lora-scripts/issues/373

**Comment by Akegarasu** [comment]
udpate submodules
