### ISSUE TITLE
commit caa05d8 版运行install-cn.ps1安装失败

### ISSUE THREAD

**Issue by Array-Cats** [Akegarasu/lora-scripts#379]
报错界面如下：
![7804657f4faa223bdc9ef67ae8abd119](https://github.com/Akegarasu/lora-scripts/assets/33084797/51e7c6af-3a9e-4369-bc5d-b84fb66fc3ac)

目前出现该报错的操作：
1.旧版执行git clone --recurse-submodules后运行install-cn.ps1
2.旧版执行git clone --recurse-submodules后运行install-cn.ps1，第一次出现报错删除venv文件夹后再次运行install-cn.ps1
3.执行git clone --recurse-submodules https://github.com/Akegarasu/lora-scripts全新下载后执行install-cn.ps1

**Comment by lhl1115** [comment]
同样的问题，windows平台
1. git clone --recurse-submodules https://github.com/Akegarasu/lora-scripts
2. 执行install-cn.ps1
3. 报错和主楼相同

直接下载Release v1.83成功安装
