### ISSUE TITLE
If xformers install way can be optimize?

### ISSUE THREAD

**Issue by killermyth** [Akegarasu/lora-scripts#38]
pip install git+https://github.com/facebookresearch/xformers.git@0bad001ddd56c080524d37c84ff58d9cd030ebfd

this commond error like below

fatal: 无法访问 'https://github.com/facebookresearch/xformers.git/'：Failed to connect to github.com port 443 after 130947 ms: 连接超时

if there is another way to install xformers?

**Comment by Georgebillion** [comment]
pip install --pre -U xformers
