### ISSUE TITLE
在linux上单卡lora训练时报错

### ISSUE THREAD

**Issue by ssdwsx** [Akegarasu/lora-scripts#387]
<img width="878" alt="屏幕截图 2024-03-14 100951" src="https://github.com/Akegarasu/lora-scripts/assets/163369063/64742c4b-90c3-461e-adf4-7b0dd1fb0329">

**Comment by ssdwsx** [comment]
求大佬们帮忙看下

**Comment by jiajie999** [comment]
看起来是依赖库版本问题，你用项目里的安装脚本装依赖，不要用conda试试
