### ISSUE TITLE
正则化图片不识别

### ISSUE THREAD

**Issue by MrZhongzq** [Akegarasu/lora-scripts#39]
![-261d98a99e722706](https://user-images.githubusercontent.com/108169409/226097384-4baf5c5c-7362-46ba-9cd8-7f2b897a2482.jpg)
![-6b45427c221a225](https://user-images.githubusercontent.com/108169409/226097388-a670d237-9aff-4d49-b4ad-4bb90a3f9cb2.jpg)
我已经设定正则化图集的路径，并且正则化图集文件夹里也是有东西的，但是仍然提示无正则化图像。

**Comment by MrZhongzq** [comment]
已解决

**Comment by yangsendyx** [comment]
> 

老哥，你是怎么解决的？

**Comment by dizhenx** [comment]
> 已解决

怎么解决的？

**Comment by brian95827** [comment]
> > 已解决
> 
> 怎么解决的？

同问，我也识别不到
