### ISSUE TITLE
sd_xl finetune保存模型时，ram占用15g+，超出则报错

### ISSUE THREAD

**Issue by giteeeeee** [Akegarasu/lora-scripts#390]
windows, sd_xl finetune + text encoder，训练结束保存模型时，内存会逐渐从~6g涨到15g+：

![ramdemo](https://github.com/Akegarasu/lora-scripts/assets/89521447/8c5d87d9-42cd-45fe-9a11-1316e096f1b4)

如果最后超出最大内存，则会memory issue报错，训练失败，模型不会被保存

虽然不是bug，但不知能否优化一下保存模型时的内存占用？比如在保存模型时offload一些不需要的模块，或是当内存100%时取用硬盘空间当内存之类的

**Comment by Akegarasu** [comment]
调大虚拟内存 模型保存时相关代码应该没有修改
