### ISSUE TITLE
wandb 只显示2个loss图表

### ISSUE THREAD

**Issue by brian95827** [Akegarasu/lora-scripts#393]
wandb 只显示2个loss图表，缺少`loss/epoch` 图表
```
wandb: WARNING Step only supports monotonically increasing values, use define_metric to set a custom x axis. For details see: https://wandb.me/define-metric
wandb: WARNING (User provided step: 1 is less than current step: 403. Dropping entry: {'loss/epoch': 0.06223894401324021, '_timestamp': 1710754420.8024263}).
```

**Comment by brian95827** [comment]
看了一下，好像代码也不在这个项目。。

**Comment by Akegarasu** [comment]
其他的图标wandb网页上可以自己调出来吧

**Comment by brian95827** [comment]
> 其他的图标wandb网页上可以自己调出来吧

其他的图表都能调出来，就这个`loss/epoch`死活调不出来。
我估计这个表的数据压根就没被记录上去。。

看上面的日志说：`User provided step: 1 is less than current step: 403.`
我估计是日志的单位冲突了。记录数据的时候把`epoch`记录成`step`了，当跑了`1 epoch`（也就是`403 step`） 准备记录日志的时候，传了 `1 step` 上去。根据wandb的记录实际已经跑了`403 step`，但是传的数据是`1 step`，两个数据明显不一致，然后被当做错误数据丢掉了。
