### ISSUE TITLE
linux云服务器上运行时的问题

### ISSUE THREAD

**Issue by Shexiaox** [Akegarasu/lora-scripts#399]
这里有一个本地的云服务器，运行run_gui.sh后，没有什么报错，但是页面只有文字，而且无法打开二级菜单
![QQ截图20240325144246](https://github.com/Akegarasu/lora-scripts/assets/79243782/814a60dd-9711-4f00-a6bc-46f45bf34c61)
![QQ截图20240325144227](https://github.com/Akegarasu/lora-scripts/assets/79243782/4d7deebb-6a34-4b20-b0cc-46d7757a472a)

**Comment by Shexiaox** [comment]
![QQ截图20240325144948](https://github.com/Akegarasu/lora-scripts/assets/79243782/e9274e6e-c241-4bce-bc8d-121719842b24)

**Comment by lipeng1109** [comment]
我直接访问都访问不到，tensorboard倒是可以访问
