### ISSUE TITLE
linux 系统安装环境出错

### ISSUE THREAD

**Issue by edisonblack55555** [Akegarasu/lora-scripts#4]
![image](https://user-images.githubusercontent.com/117357308/218041056-59472795-e8e1-4799-8e07-8144434f70ce.png)
昨天晚上还能正常运行，今天运行就失败了，用的是python已经更新成3.10.8版本的colab上面运行的

**Comment by Akegarasu** [comment]
![}_G1E$8X 5`~ B{X8E1FU0P](https://user-images.githubusercontent.com/36563862/218079635-acd17639-3173-4f7d-a371-7d1a29578b26.jpg)

**Comment by edisonblack55555** [comment]
hhhc,抱歉，那我还是把完整的记录上传一下吧
[错误.txt](https://github.com/Akegarasu/lora-scripts/files/10708147/default.txt)


> ![}_G1E$8X 5`~ B{X8E1FU0P](https://user-images.githubusercontent.com/36563862/218079635-acd17639-3173-4f7d-a371-7d1a29578b26.jpg)

**Comment by Akegarasu** [comment]
尝试指定 `altair==4.2.0`

**Comment by edisonblack55555** [comment]
> altair

谢谢
