### ISSUE TITLE
linux多机多卡训练需要改什么参数吗

### ISSUE THREAD

**Issue by sunnyhi** [Akegarasu/lora-scripts#41]
使用两台linux服务器，每台上面有一张a10，运行train.sh后感觉两台机器在独立训练，有什么关键配置要改吗？
这两台机器跑accelerate官方的样例nlp_example.py是成功的

**Comment by SrlyNb666** [comment]
阿哲，想问一下怎么改配置呢，我是一机双卡，train.sh文件里我加mult_gpu没用，只能一个卡在跑，想请教一下

**Comment by asizk** [comment]
> 找到原因了，accelerate没有读默认配置，读的是huggingface目录下的配置，进行对应的配置修改就好了

你好，请问我修改了accelerate.config 我该如何修改启动脚本train_by_toml.sh呢，
