### ISSUE TITLE
标签编辑器启动失败

### ISSUE THREAD

**Issue by Cuiyaxuanzzz** [Akegarasu/lora-scripts#419]
![image](https://github.com/Akegarasu/lora-scripts/assets/49049021/28fa235e-6536-4461-846b-c03f8b98fa78)

**Comment by Tamako888** [comment]
Python3.10以下不支持用“|”来表示联合类型，简单的处理方式是找到gr_hijack.py的23行，即postprocess函数，把y的类型删了即可解决。
