### ISSUE TITLE
断点续训resume时的epoch计数问题

### ISSUE THREAD

**Issue by Taichipeace** [Akegarasu/lora-scripts#420]
首先，感谢各位大佬提供这么好用的工具。

目前遇到的困惑是：
假如我从第16个epoch续训，
续训开始后，又会从epoch1开始计数，
直到max_train_epochs结束，
实际相当于训练了 16+max_train_epochs 个epoch，
这中间还会覆盖掉续训之前保存的safetensors文件，
感觉有点别扭。

可否改成：
从第16个epoch续训，
计数也从16开始，
直到max_train_epochs结束。

再次感谢。

**Comment by Pevernow** [comment]
好问题

**Comment by douniwanjin** [comment]
你好  是不是只能训练中途端断开的 继续训练(比如要训练30轮  30钱短的才可以继续呢)
我训练完30轮再想加几轮失败。比如31,32,33,34,35，是不是不可以

**Comment by Akegarasu** [comment]
#524
