### ISSUE TITLE
使用v2-1_768-ema-pruned.safetensors训练lora报错

### ISSUE THREAD

**Issue by too-difficult-to-study** [Akegarasu/lora-scripts#421]
请问大佬出现如下报错是为什么呀？
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".

**Comment by Elsa0333** [comment]
我好像也是这样

**Comment by dmdomo** [comment]
我也遇到同样的问题，通过降低transformers版本可以解决，
~~`transformers==4.36.2 `~~
使用：
`transformers==4.30.2`
