### ISSUE TITLE
标签编辑器无法加载图片和标签

### ISSUE THREAD

**Issue by sunsn1997** [Akegarasu/lora-scripts#433]
后台显示：
-00%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 24.85it/s]
0it [00:00, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 27.24it/s]
0it [00:00, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 25.33it/s]

但是前端在数据集图片、选择图片、右侧标签过滤器都显示error：
选择图片
Displayed Images : 0 / 0 total
Current Tag Filter :
Current Selection Filter : 0 images

**Comment by izumookuni** [comment]
需要保证huggingface.co能够访问，会下载一些必要的文件。

**Comment by Jacky-MYQ** [comment]
哥你这个怎么解决的，我也是这个问题
