### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by DarkAlchy** [Akegarasu/lora-scripts#443]
How do we get this in English?

**Comment by brian95827** [comment]
前端代码在这。[https://github.com/hanamizuki-ai/lora-gui-dist/tree/456e801240ce1d320760c63cf43d2d49210b108e](https://github.com/hanamizuki-ai/lora-gui-dist/tree/456e801240ce1d320760c63cf43d2d49210b108e)
你的issue提错了地儿~应该去前端问问。

---

现在网页的一键翻译已经很成熟了，看不懂的话直接翻译就好了。

与其等翻译，不如自己翻译。我跑英文项目也是这样的。
