### ISSUE TITLE
ERROR: No matching distribution found for xformers==0.0.25+cu118

### ISSUE THREAD

**Issue by Amazon90** [Akegarasu/lora-scripts#446]
ERROR: 
```
ERROR: Could not find a version that satisfies the requirement xformers==0.0.25+cu118 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.post1, 0.0.27.dev792)
ERROR: No matching distribution found for xformers==0.0.25+cu118
```

WARNING: 
```
WARNING: The candidate selected for download or install is a yanked version: 'opencv-python' candidate (version 4.7.0.68 at https://files.pythonhosted.org/packages/80/5b/6eee3a1dc0f296904f44a13749f3b2cd29569c817aa931ead50c4d085d51/opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (from https://pypi.org/simple/opencv-python/) (requires-python:>=3.6))
Reason for being yanked: Deprecated, use 4.7.0.71
```

DEPRECATION: 
```
DEPRECATION: ffmpy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
DEPRECATION: lycoris-lora is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by japppie** [comment]
Same issue. I'm installing by running install.ps1 in powershell.. Everything installs fine except for this error:

ERROR: Could not find a version that satisfies the requirement xformers==0.0.25+cu118 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.post1, 0.0.27.dev845, 0.0.27.dev850, 0.0.27, 0.0.28.dev851)
ERROR: No matching distribution found for xformers==0.0.25+cu118

**Comment by japppie** [comment]
I think I fixed this by manually installing xformers into my venv.

Go to the root of the repo, open cmd and type
venv/scripts/activate

then type
pip install torch==2.2.1+cu118 xformers --index-url https://download.pytorch.org/whl/cu118

this forced to install the correct torch with accompanying xformers

**Comment by taliove** [comment]
> I think I fixed this by manually installing xformers into my venv.
> 
> Go to the root of the repo, open cmd and type venv/scripts/activate
> 
> then type pip install torch==2.2.1+cu118 xformers --index-url https://download.pytorch.org/whl/cu118
> 
> this forced to install the correct torch with accompanying xformers

使用python 3.10.6，按照这个方法以及结合这个 https://blog.csdn.net/u011573054/article/details/133939511 测试成功。
