### ISSUE TITLE
Cannot import settings from a toml file. 无法通过toml文件导入完整的配置

### ISSUE THREAD

**Issue by power88** [Akegarasu/lora-scripts#449]
如题所示，在导入设置时，若使用了lycoris模块(lycoris.kohya)，有关lycoris的细节参数无法导入(比如lycoris_algo;conv_dim;conv_alpha;lokr_factor等)
As the title metioned, when using network module lycoris.kohya. Can not load settings from toml. Such as lycoris_algo, conv_dim, conv_alpha, lokr_factor, etc.

**Comment by Akegarasu** [comment]
这是bug，等待修复吧

**Comment by power88** [comment]
ok
