### ISSUE TITLE
训练xl 报错

### ISSUE THREAD

**Issue by skywalker17753271233** [Akegarasu/lora-scripts#455]
加载text encoder时报错：Missing key(s) in state_dict: "text_model.embeddings.position_ids". ，应该怎么解决

**Comment by wckaleb1** [comment]
> 加载text encoder时报错：Missing key(s) in state_dict: "text_model.embeddings.position_ids". ，应该怎么解决

我训练1.5 SD的时候也出现这个报错，你是咋解决的？
