### ISSUE TITLE
Tagger 打标签失败

### ISSUE THREAD

**Issue by blackWins** [Akegarasu/lora-scripts#460]
**使用 WD 1.4 标签器 打标签出现异常，能指导下怎么处理吗？
Can you provide guidance on how to handle abnormal labeling using WD 1.4 labeler?**

17:07:51-274145 INFO     Starting SD-Trainer Mikazuki GUI...
17:07:51-277145 INFO     Base directory: D:\AI\lora-scripts, Working directory: D:\AI\lora-scripts
17:07:51-278145 INFO     Windows Python 3.10.0 D:\AI\lora-scripts\venv\Scripts\python.exe
17:07:51-279146 INFO     detected locale zh_CN, use pip mirrors
17:07:51-286144 INFO     Starting tageditor...
17:07:51-291146 INFO     Starting tensorboard...
17:07:51-347146 INFO     Server started at http://127.0.0.1:28000
TensorFlow installation not found - running with reduced feature set.
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
17:07:52-970956 INFO     Torch 2.2.1+cu118
17:07:52-985953 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:07:52-987955 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 22528 Arch (7, 5) Cores 68
found 8 image(s)
Loading wd14-convnextv2-v2 model file from SmilingWolf/wd-v1-4-convnextv2-tagger-v2
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
  |     await response(scope, receive, send)
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    |     await func()
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    |     return await super().stream_response(send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 262, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
    |     raise app_exc
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    |     raise exc
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 69, in app
    |     await response(scope, receive, send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 174, in __call__
    |     await self.background()
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\background.py", line 43, in __call__
    |     await task()
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\background.py", line 28, in __call__
    |     await run_in_threadpool(self.func, *self.args, **self.kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    |     return await future
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    |     result = context.run(func, *args)
    |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 356, in on_interrogate
    |     ratings, tags = interrogator.interrogate(image)
    |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 163, in interrogate
    |     self.load()
    |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 126, in load
    |     model_path, tags_path = self.download()
    |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 119, in download
    |     model_path = Path(hf_hub_download(
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    |     return fn(*args, **kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
    |     metadata = get_hf_file_metadata(
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    |     return fn(*args, **kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
    |     r = _request_wrapper(
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
    |     response = _request_wrapper(
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
    |     response = get_session().request(method=method, url=url, **params)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\sessions.py", line 589, in request
    |     resp = self.send(prep, **send_kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\sessions.py", line 703, in send
    |     r = adapter.send(request, **kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    |     return super().send(request, *args, **kwargs)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\adapters.py", line 694, in send
    |     raise ProxyError(e, request=request)
    | requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /SmilingWolf/wd-v1-4-convnextv2-tagger-v2/resolve/v2.0/model.onnx (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))"), '(Request ID: d48bb4e2-8089-4c3a-bc6e-65c95c9c54c4)')
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 277, in __call__
    |     await wrap(partial(self.listen_for_disconnect, receive))
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
    |     await func()
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 250, in listen_for_disconnect
    |     message = await receive()
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 564, in receive
    |     await self.message_event.wait()
    |   File "C:\Users\kity\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 213, in wait
    |     await fut
    | asyncio.exceptions.CancelledError: Cancelled by cancel scope 18c1ace5420
    |
    | During handling of the above exception, another exception occurred:
    |
    | Exception Group Traceback (most recent call last):
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    |     await response(scope, receive, send)
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 270, in __call__
    |     async with anyio.create_task_group() as task_group:
    |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
    |     raise BaseExceptionGroup(
    | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
      |     self._prepare_proxy(conn)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
      |     conn.connect()
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connection.py", line 624, in connect
      |     self.sock = sock = self._connect_tls_proxy(self.host, sock)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connection.py", line 698, in _connect_tls_proxy
      |     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
      |     ssl_sock = ssl_wrap_socket(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
      |     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
      |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      |   File "C:\Users\kity\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
      |     return self.sslsocket_class._create(
      |   File "C:\Users\kity\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
      |     self.do_handshake()
      |   File "C:\Users\kity\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
      |     self._sslobj.do_handshake()
      | FileNotFoundError: [Errno 2] No such file or directory
      |
      | The above exception was the direct cause of the following exception:
      |
      | urllib3.exceptions.ProxyError: ('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory'))
      |
      | The above exception was the direct cause of the following exception:
      |
      | Traceback (most recent call last):
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\adapters.py", line 667, in send
      |     resp = conn.urlopen(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
      |     retries = retries.increment(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
      |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
      | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /SmilingWolf/wd-v1-4-convnextv2-tagger-v2/resolve/v2.0/model.onnx (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
      |
      | During handling of the above exception, another exception occurred:
      |
      | Traceback (most recent call last):
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 273, in wrap
      |     await func()
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
      |     return await super().stream_response(send)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 262, in stream_response
      |     async for chunk in self.body_iterator:
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
      |     raise app_exc
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
      |     await self.app(scope, receive_or_disconnect, send_no_error)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
      |     raise exc
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
      |     await self.app(scope, receive, sender)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
      |     raise e
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
      |     await self.app(scope, receive, send)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
      |     await route.handle(scope, receive, send)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
      |     await self.app(scope, receive, send)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 69, in app
      |     await response(scope, receive, send)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\responses.py", line 174, in __call__
      |     await self.background()
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\background.py", line 43, in __call__
      |     await task()
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\background.py", line 28, in __call__
      |     await run_in_threadpool(self.func, *self.args, **self.kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
      |     return await anyio.to_thread.run_sync(func, *args)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
      |     return await get_async_backend().run_sync_in_worker_thread(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
      |     return await future
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
      |     result = context.run(func, *args)
      |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 356, in on_interrogate
      |     ratings, tags = interrogator.interrogate(image)
      |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 163, in interrogate
      |     self.load()
      |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 126, in load
      |     model_path, tags_path = self.download()
      |   File "D:\AI\lora-scripts\mikazuki\tagger\interrogator.py", line 119, in download
      |     model_path = Path(hf_hub_download(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
      |     return fn(*args, **kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
      |     metadata = get_hf_file_metadata(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
      |     return fn(*args, **kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
      |     r = _request_wrapper(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
      |     response = _request_wrapper(
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
      |     response = get_session().request(method=method, url=url, **params)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\sessions.py", line 589, in request
      |     resp = self.send(prep, **send_kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\sessions.py", line 703, in send
      |     r = adapter.send(request, **kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
      |     return super().send(request, *args, **kwargs)
      |   File "D:\AI\lora-scripts\venv\lib\site-packages\requests\adapters.py", line 694, in send
      |     raise ProxyError(e, request=request)
      | requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /SmilingWolf/wd-v1-4-convnextv2-tagger-v2/resolve/v2.0/model.onnx (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))"), '(Request ID: d48bb4e2-8089-4c3a-bc6e-65c95c9c54c4)')
      +------------------------------------

**Comment by N-E-K-O** [comment]
遇到了同样的打标签失败的问题。
进一步，使用本地的把标签打好后，进行训练依然报错：
```
22:29:11-410484 INFO     Torch 2.0.1+cu118                                      
22:29:11-468199 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700             
22:29:11-491475 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12044 
                         Arch (8, 6) Cores 28                                   
22:32:19-736050 INFO     Training started with config file /                    
                         训练开始，使用配置文件:                                
                         /root/lora-scripts/config/autosave/20240722-223219.toml
22:32:19-739452 INFO     Task 530b7459-6d99-42fa-8995-6dfc78477660 created      
Loading settings from /root/lora-scripts/config/autosave/20240722-223219.toml...
/root/lora-scripts/config/autosave/20240722-223219
prepare tokenizer
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 998, in <module>
    trainer.train(args)
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 154, in train
    tokenizer = self.load_tokenizer(args)
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 107, in load_tokenizer
    tokenizer = train_util.load_tokenizer(args)
  File "/root/lora-scripts/sd-scripts/library/train_util.py", line 3850, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1951, in from_pretrained
    resolved_config_file = cached_file(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))"), '(Request ID: 6b6695b4-9c0e-4776-9b9b-326929f92dfc)')
22:32:36-034499 ERROR    Training failed / 训练失败 
```
