### ISSUE TITLE
运行install-cn.ps1命令，提示已经安装成功，训练时候提示“Error caught was: No module named 'triton'“

### ISSUE THREAD

**Issue by Yangrunhu** [Akegarasu/lora-scripts#47]
如题，这个应该怎么解决呢？

**Comment by Yangrunhu** [comment]
系统是windows11，已安装cuda 12.1

**Comment by Akegarasu** [comment]
不影响训练

**Comment by HEXtoDEC** [comment]
这个玩意好像没有windows版本，但是我启动之后就直接告诉我训练成功了？但实际没有任何输出。

**Comment by RyanWestinLiu** [comment]
`A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer`

安装成功，并重装过无数次，都是上述提示然后卡死。任务管理器CPU占用为0%。
