### ISSUE TITLE
flux 训练卡在模型类型检测，无论哪种模型都无法通过检测

### ISSUE THREAD

**Issue by pzzmyc** [Akegarasu/lora-scripts#470]
尝试过diffusers格式和sft和safetensors格式，似乎只有diffusers格式通过了检测，但还是报错

![image](https://github.com/user-attachments/assets/2f939676-9f3e-44c9-b7c4-9625169a10ae)

**Comment by yxyxyz6** [comment]
同上

**Comment by whmc76** [comment]
+1
![image](https://github.com/user-attachments/assets/c2c315fa-7ffe-4fc2-8dfa-1a9f3d8443c9)

**Comment by Akegarasu** [comment]
已修复 更新一下
