### ISSUE TITLE
训练任务提交失败：Pretrained model is not a Stable Diffusion checkpoint / 校验失败：底模不是 Stable Diffusion 模型

### ISSUE THREAD

**Issue by ppfly** [Akegarasu/lora-scripts#472]
选任何模型点开始训练都提示这个

**Comment by xdtxkbf** [comment]
同样的

**Comment by weilin9999** [comment]
me too

**Comment by h1shen** [comment]
me three

**Comment by Akegarasu** [comment]
已修复

**Comment by rwywenyi** [comment]
> 已修复

14:55:15-879812 INFO     Torch 2.2.1+cu118
14:55:15-897624 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8801
14:55:15-917990 INFO     Torch detected GPU: NVIDIA A100-SXM4-80GB VRAM 81100 Arch (8, 0) Cores 108
15:01:57-470580 ERROR    Can't match model type from /aigc-nas01/renwenyi/sgp_download/FLUX/flux1-dev.safetensors
15:02:03-365851 ERROR    Can't match model type from /aigc-nas01/renwenyi/sgp_download/FLUX/flux1-dev.safetensors
15:02:11-047984 ERROR    Can't match model type from /aigc-nas01/renwenyi/sgp_download/FLUX/flux1-dev.safetensors
15:03:13-006875 ERROR    Can't match model type from /aigc-nas01/renwenyi/sgp_download/FLUX/flux1-dev.safetensors
使用最新版的代码，还是报错

**Comment by Drawthe** [comment]
请问具体修改哪些呢？我需要怎么操作才能正常运行？

**Comment by momomomo-fff** [comment]
the same problem in 26/03/07
