### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by h1shen** [Akegarasu/lora-scripts#473]
在训练flux lora时raise error
具体报错信息
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\sd-scripts\flux_train_network.py", line 409, in <module>
    trainer.train(args)
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\sd-scripts\train_network.py", line 537, in train
    unet.to(accelerator.device, dtype=unet_weight_dtype)  # this seems to be safer than above
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\python\lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\python\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\python\lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
    param_applied = fn(param)
  File "E:\train\lora-scripts-v1.8.5(1)\lora-scripts-v1.8.5\python\lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

本机配置32.0 GB内存 4090 24G

python环境 
absl-py==1.4.0
accelerate==0.33.0
aiofiles==23.2.1
aiohttp==3.8.4
aiosignal==1.3.1
albumentations==1.3.0
altair==4.2.2
anyio==3.6.2
appdirs==1.4.4
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
bitsandbytes==0.43.3
cachetools==5.3.0
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.2.0
cycler==0.12.1
dadaptation==3.1
diffusers==0.25.0
docker-pycreds==0.4.0
easygui==0.98.3
einops==0.7.0
entrypoints==0.4
fairscale==0.4.13
fastapi==0.95.1
ffmpy==0.3.1
filelock==3.12.0
flatbuffers==23.5.9
fonttools==4.44.1
frozenlist==1.3.3
fsspec==2023.5.0
ftfy==6.1.1
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.18.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
gradio==3.44.2
gradio_client==0.5.0
grpcio==1.54.2
h11==0.14.0
h5py==3.8.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.24.5
humanfriendly==10.0
idna==3.4
imageio==2.28.1
imagesize==1.4.1
importlib-metadata==6.6.0
importlib-resources==6.1.1
invisible-watermark==0.2.0
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.5
lazy_loader==0.2
libclang==16.0.0
lightning-utilities==0.8.0
linkify-it-py==2.0.2
lion-pytorch==0.1.2
lycoris-lora==2.1.0.post3
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.8.1
mdit-py-plugins==0.3.3
mdurl==0.1.1
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.1
numpy==1.24.3
oauthlib==3.2.2
onnxruntime==1.17.1
onnxruntime-gpu==1.17.1
open-clip-torch==2.20.0
opencv-python==4.7.0.68
opencv-python-headless==4.7.0.72
opt-einsum==3.3.0
orjson==3.9.10
packaging==23.1
pandas==2.0.1
pathtools==0.1.2
Pillow==9.5.0
prodigyopt==1.0
protobuf==3.19.6
psutil==5.9.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.7
pydub==0.25.1
Pygments==2.16.1
pyparsing==3.1.1
pyre-extensions==0.0.29
pyreadline3==3.4.1
pyrsistent==0.19.3
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.0
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
qudida==0.0.4
regex==2023.5.5
requests==2.28.2
requests-oauthlib==1.3.1
rich==13.7.0
rsa==4.9
safetensors==0.4.2
scikit-image==0.20.0
scikit-learn==1.2.2
scipy==1.10.1
semantic-version==2.10.0
sentencepiece==0.2.0
sentry-sdk==1.22.2
setproctitle==1.3.2
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
starlette==0.26.1
sympy==1.12
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.10.1
tensorflow-estimator==2.10.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.3.0
threadpoolctl==3.1.0
tifffile==2023.4.12
timm==0.6.12
tokenizers==0.19.1
toml==0.10.2
toolz==0.12.0
torch==2.2.1+cu118
torchmetrics==0.11.4
torchvision==0.17.1+cu118
tqdm==4.65.0
transformers==4.44.0
typing-inspect==0.8.0
typing_extensions==4.10.0
tzdata==2023.3
uc-micro-py==1.0.2
urllib3==1.26.15
uvicorn==0.22.0
voluptuous==0.13.1
wandb==0.16.2
wcwidth==0.2.6
websockets==11.0.3
Werkzeug==2.3.4
wrapt==1.15.0
xformers==0.0.24+cu118
yarl==1.9.2
zipp==3.15.0

看了一些issue很多说是显存或内存不足 有遇到和我一样情况的同学么

**Comment by qqliaoxin** [comment]
me too!!

**Comment by Akegarasu** [comment]
使用fp16的flux模型
