### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

### ISSUE THREAD

**Issue by GFY2000** [Akegarasu/lora-scripts#477]
![image](https://github.com/user-attachments/assets/6ffeb4bf-a67a-4fc0-9419-0dd6eabd51b8)
为什么我训练flux的lora模型时会报这个错误

**Comment by Akegarasu** [comment]
使用fp16的flux模型

**Comment by GFY2000** [comment]
> 使用fp16的通量模型

好的，我试试，谢谢！

**Comment by GFY2000** [comment]
![image](https://github.com/user-attachments/assets/478c69ad-8d73-4a54-9828-3214a89a29cd)
请问这个我应该修改哪里

**Comment by Akegarasu** [comment]
use flux.1 dev model https://huggingface.co/black-forest-labs/FLUX.1-dev

**Comment by Akegarasu** [comment]
related issues
- https://github.com/kohya-ss/sd-scripts/issues/1454

**Comment by GFY2000** [comment]
好的谢谢！

**Comment by shipoyewu** [comment]
请问训练flux的lora需要最少多少显存呀，V100 都不够看。

**Comment by GFY2000** [comment]
> 请问训练flux的lora需要最少多少显存呀，V100都不够看。

我用的A800，80G的，但是我训练的时候显存占用能达到60%，也不知道是不是我参数有问题。。。。

**Comment by shipoyewu** [comment]
您好，您的邮件我已收到!祝：工作商祺!

**Comment by maskerwen** [comment]
13:41:09-090250 INFO     Torch 2.0.0+cu118
13:41:09-105200 WARNING  Torch version is lower than 2.3.0, which may not be able to train FLUX model properly.
                         Consider upgrading to a newer version.
13:41:09-106197 WARNING  ！！！Torch 版本低于 2.3.0，将无法正常训练 FLUX 模型。请考虑升级到更新的版本。！！！

我已经升级到2.4.0 cuda 12.4 为啥显示降级了
