### ISSUE TITLE
RuntimeError: "index_select_cuda" not implemented for 'Float8_e4m3fn'

### ISSUE THREAD

**Issue by cailiyuan888** [Akegarasu/lora-scripts#483]
葉宝，直接练内存不够报错，然后下面勾选FP8精度后 显存刚刚好跑过去了  但是最后报错这个RuntimeError: "index_select_cuda" not implemented for 'Float8_e4m3fn' 
![Uploading 微信图片_20240824134222.png…]()

**Comment by ppfly** [comment]
+1

**Comment by DoiryCool** [comment]
+1

**Comment by cailiyuan888** [comment]
我看了原训练器的大佬回答的是t5xx暂时不支持fp8的版本嘛    
 [kohya-ss](https://github.com/kohya-ss) commented [2 days ago](https://github.com/kohya-ss/sd-scripts/issues/1512#issuecomment-2308356760)
We will support the T5XXL to run on fp8 in the future, so please wait a little longer.
只能等了 0.0.
