### ISSUE TITLE
是不是需要升级torch版本？

### ISSUE THREAD

**Issue by ljjsimon** [Akegarasu/lora-scripts#49]
安装的时候报错：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.14.0 requires torch==1.13.0, but you have torch 1.12.1+cu116 which is incompatible.
torchaudio 0.13.0+cpu requires torch==1.13.0, but you have torch 1.12.1+cu116 which is incompatible.

**Comment by Georgebillion** [comment]
请自行查找一下相关版本安装，这玩意我记得能找

**Comment by Akegarasu** [comment]
你自己的环境问题，尝试换个新的虚拟环境
