### ISSUE TITLE
sdxl训练出错

### ISSUE THREAD

**Issue by weilin9999** [Akegarasu/lora-scripts#492]
Traceback (most recent call last):
  File "/root/lora-scripts/./sd-scripts/sdxl_train_network.py", line 210, in <module>
    trainer.train(args)
  File "/root/lora-scripts/sd-scripts/train_network.py", line 1088, in train
    text_encoder_conds is None
UnboundLocalError: local variable 'text_encoder_conds' referenced before assignment

**Comment by DuShunpeng** [comment]
shuffle_caption=true 就会有这个问题

**Comment by cqarray** [comment]
> shuffle_caption=true 的时候，要求catch_set_encode_outputs和catch_set_encode_outputs_to_disk就不能开启。如果过后面两个没有开启了，就会报这个错误。 因此，不能开启shuffle_caption。把catch_set_encode_outputs和catch_set_encode_outputs_to_disk开启就行。 但这的确是个问题，估计koya没有测试到。

catch_set_encode_outputs和catch_set_encode_outputs_to_disk 在哪里进行开启，我也遇到这个问题了

**Comment by cqarray** [comment]
![无标题](https://github.com/user-attachments/assets/8935441f-a35b-42f6-ab3b-3ab84012dcdc)
遇到一样的情况

**Comment by X-T-E-R** [comment]
> > shuffle_caption=true 的时候，要求catch_set_encode_outputs和catch_set_encode_outputs_to_disk就不能开启。如果过后面两个没有开启了，就会报这个错误。 因此，不能开启shuffle_caption。把catch_set_encode_outputs和catch_set_encode_outputs_to_disk开启就行。 但这的确是个问题，估计koya没有测试到。
> 
> catch_set_encode_outputs和catch_set_encode_outputs_to_disk 在哪里进行开启，我也遇到这个问题了

应该是更新后才发生的，同样的参数新版本会发生问题

**Comment by cqarray** [comment]
> > > shuffle_caption=true 的时候，要求catch_set_encode_outputs和catch_set_encode_outputs_to_disk就不能开启。如果过后面两个没有开启了，就会报这个错误。 因此，不能开启shuffle_caption。把catch_set_encode_outputs和catch_set_encode_outputs_to_disk开启就行。 但这的确是个问题，估计koya没有测试到。
> > 
> > 
> > catch_set_encode_outputs和catch_set_encode_outputs_to_disk 在哪里进行开启，我也遇到这个问题了
> 
> 应该是更新后才发生的，同样的参数新版本会发生问题

确实，这边降低版本到v 1.8.3运行就正常了

**Comment by Mikanlover** [comment]
![Capture d'écran 2024-08-29 163819](https://github.com/user-attachments/assets/ed0e30d6-b10b-4c84-b4a9-a040ac948fd6)
我v1.8.3也还是有问题

**Comment by ilyq** [comment]
![image](https://github.com/user-attachments/assets/10ad2fdd-c7c3-4cc6-bae6-cce94b9c9ef9)
看样子是https://github.com/kohya-ss/sd-scripts 有问题，回滚下代码就可以了
git checkout 9e72be0a13fcd09df23406f49dc0fd7ec288c713, 这个测试通过, 我跑的是1.5的lora
这个72287d39c76176c0e1c16e8da4f5ddc6f94ea7d6 commit应该也可以，这个代码会新一些，但没有测试

**Comment by SimomSimonLiu** [comment]
![image](https://github.com/user-attachments/assets/4d0b230e-9727-4c66-b462-e32ae8213ea6)
我好像遇到了同样的问题吗

**Comment by Akegarasu** [comment]
fixed
