### ISSUE TITLE
flux 训练失败 info = model.load_state_dict(sd, strict=False, assign=True) TypeError: Module.load_state_dict() got an unexpected keyword argument 'assign'

### ISSUE THREAD

**Issue by liujiufu-victor** [Akegarasu/lora-scripts#493]
![1724944610474](https://github.com/user-attachments/assets/ef464fe3-7c80-4077-ba69-54966f420f45)
 info = model.load_state_dict(sd, strict=False, assign=True)
TypeError: Module.load_state_dict() got an unexpected keyword argument 'assign'

**Comment by lyj1587** [comment]
I meet this problem, too. And don't know why.

**Comment by jasonlbx13** [comment]
请问最新版本的训练选项里只有sd和sdxl，是如何训练的flux lora呢？

**Comment by a442509097** [comment]
Same here.

**Comment by jasonlbx13** [comment]
需要升级pytorch的版本，旧版本加载模型的方法没有assign这个参数

pytorch 2.0:
https://github.com/pytorch/pytorch/blob/v2.0.0/torch/nn/modules/module.py

def load_state_dict(self, state_dict: Mapping[str, Any],
                    strict: bool = True):

pytorch 2.3:
https://github.com/pytorch/pytorch/blob/v2.3.0/torch/nn/modules/module.py

def load_state_dict(self, state_dict: Mapping[str, Any],
                    strict: bool = True, assign: bool = False):

**Comment by Akegarasu** [comment]
update pytorch
