### ISSUE TITLE
torch 2.3.1+cuda12.1 with the latest code, but got the train error when use single GPU, pls help

### ISSUE THREAD

**Issue by lilyzlt** [Akegarasu/lora-scripts#499]
## error
When I use 2 GPU to train flux lora, everything is fine, successful training~, but when I use one GPU or start with 2GPU, but use one, it start to have the error bellow, the code is latest commit ID: 1767dd101e63a50b159fe4ce55754caaf0078cb8; 
I tried :
export NCCL_DEBUG=INFO
export CUDA_DEVICE_ORDER="PCI_BUS_ID"
export NCCL_IB_DISABLE=1

![image](https://github.com/user-attachments/assets/8e6d61d2-0f79-4d00-9123-4ebca99b6317)
![image](https://github.com/user-attachments/assets/23776f2c-6664-444e-90a7-6da7aeab7bca)
###  Environment :
lion-pytorch                 0.1.2
open-clip-torch              2.20.0
pytorch-lightning            1.9.0
torch                        2.3.1+cu121
torchaudio                   2.3.1+cu121
torchmetrics                 1.4.1
torchvision                  0.18.1+cu121
nvidia-nccl-cu12        2.20.5
centos 8 system
![image](https://github.com/user-attachments/assets/cceec792-d2e2-45d5-9821-b64c7055695e)
![image](https://github.com/user-attachments/assets/d322c24a-8503-4c19-b098-464a52d5ef9f)

please help!

**Comment by lilyzlt** [comment]
if I use 2 GPUs, everything is fine:
![image](https://github.com/user-attachments/assets/5c4562be-bc56-4bb7-a4ad-954ea768c395)
![image](https://github.com/user-attachments/assets/9f61af6e-2f59-4822-975a-cefd5e6606e6)

**Comment by Akegarasu** [comment]
try set CUDA_VISIBLE_DEVICES
