### ISSUE TITLE
请问怎么设置才能使用v2.1大模型呢？

### ISSUE THREAD

**Issue by petercham** [Akegarasu/lora-scripts#50]
请问怎么设置才能使用v2.1大模型呢？尝试手动在train.ps1里第101行--enable_bucket `前面加上--v2，执行会提醒v2不能同时使用clip_skip，然后注释掉clip_skip仍然运行不了

**Comment by HEXtoDEC** [comment]
我试了下，把clip_skip改为0是可以的。

**Comment by Akegarasu** [comment]
fixed
