### ISSUE TITLE
請問如何更新Torch 2.3.0版？

### ISSUE THREAD

**Issue by goukiou** [Akegarasu/lora-scripts#502]
我想訓練flux lora,但 SD-Trainer顯示需更新Torch 2.3.0版 請問要如何更新呢?我執行過以下指令,有下載某些資料,但還是無法更新。要如何切換至虛擬環境（venv）?謝謝您的回答
pip3 install torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu124

![image](https://github.com/user-attachments/assets/9738ae97-ddd5-4b8c-a7ba-7fff5a4786de)

**Comment by Akegarasu** [comment]
run install script again

**Comment by goukiou** [comment]
收到 謝謝你
Thank you

秋葉杏 ***@***.***> 於 2024年9月6日 週五 下午3:03寫道：

**Comment by goukiou** [comment]
再請問您個問題~我想用秋葉訓練器 作 FLUX LORA,但 用過"  lora-scripts-v1.9.0-cu124 "以及
"lora-scripts-v1.9.0"兩個版本都會顯示,以下的錯誤訊息,請問我是少裝了什麼嗎?或是那個參數要打開或取消呢?(參數部分我已試過逐一開關,依然顯示個著錯誤,flux
模型也重新下載過)也去B站找過類似問題~但都無解,希望秋葉老師能夠提示解決方法!(對了我的顯卡式 4070 TI SUPER 16G DRIVER
561.09) 謝謝
[image: image.png]

chung ou ***@***.***> 於 2024年9月7日 週六 下午12:11寫道：
