### ISSUE TITLE
Torch 无法使用 GPU，脚本无法识别venv中的torch版本？

### ISSUE THREAD

**Issue by giteeeeee** [Akegarasu/lora-scripts#503]
venv中的torch版本是2.4.0：
![meoww](https://github.com/user-attachments/assets/a907eec4-96ca-483f-9d0d-0d98c4d8112a)
（以上卸载指令只是查看torch版本，并未执行卸载）

但随后执行gui.py，识别的却是2.3.1的cpu版本（所以无法使用GPU）：
![meowww](https://github.com/user-attachments/assets/b54d86e3-25e0-4643-9b20-3385ffd1a7a9)

**Comment by Akegarasu** [comment]
那你用venv但python启动啊
