### ISSUE TITLE
版本过低

### ISSUE THREAD

**Issue by Lin-cabin** [Akegarasu/lora-scripts#506]
WARNING  Torch version is lower than 2.3.0, which may not be able to train FLUX model properly. Consider upgrading to a newer
                         version.
WARNING  ！！！Torch 版本低于 2.3.0，将无法正常训练 FLUX 模型。请考虑升级到更新的版本。！！！

求助，需要怎么解决

**Comment by tangooooooo** [comment]
我也想问这个问题
