### ISSUE TITLE
找不到指定模块

### ISSUE THREAD

**Issue by edisonblack55555** [Akegarasu/lora-scripts#507]
![image](https://github.com/user-attachments/assets/b88c09e3-8d85-4b99-a0fd-a6538f670958)
使用最新的压缩包解压后打开显示如下，即使进行强制更新后依然缺失

**Comment by jiewjwang** [comment]
> ![image](https://private-user-images.githubusercontent.com/117357308/366414930-b88c09e3-8d85-4b99-a0fd-a6538f670958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDg2MjUsIm5iZiI6MTcyNjEwODMyNSwicGF0aCI6Ii8xMTczNTczMDgvMzY2NDE0OTMwLWI4OGMwOWUzLThkODUtNGI5OS1hMGZkLWE2NTM4ZjY3MDk1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMjMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTkyZjc0Njg2ZmU0NWJlYTBlMTJlZDg0MjdlYjYzNWIzYWQyYzAwMzgzODllODczY2E4OWExMjliYTg0MWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xEW7L5PvhUgHvtqgINZjLrNhtqZYEndmH6ZISuGf8xM) 使用最新的压缩包解压后打开显示如下，即使进行强制更新后依然缺失

我也是这种情况呀，怎么解决的呀

**Comment by ilikeulinux** [comment]
路径不能有中文吧

**Comment by niseloli** [comment]
下載 libomp140.x86_64.dll 複製到 C:\Windows\System32
https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download

我在這裡找到的解決方法
https://github.com/Acly/krita-ai-diffusion/issues/965

**Comment by Akegarasu** [comment]
下载最新的
