### ISSUE TITLE
Flux lora训练报错

### ISSUE THREAD

**Issue by NaughtDZ** [Akegarasu/lora-scripts#509]
报错内容：
Traceback (most recent call last):
  File "L:\lora-scripts\scripts\flux_train_network.py", line 446, in <module>
    trainer.train(args)
  File "L:\lora-scripts\scripts\train_network.py", line 544, in train
    unet.to(accelerator.device, dtype=unet_weight_dtype)  # this seems to be safer than above
  File "L:\lora-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
  File "L:\lora-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "L:\lora-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "L:\lora-scripts\venv\lib\site-packages\torch\nn\modules\module.py", line 1167, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
18:57:07-991950 ERROR    Training failed / 训练失败
----------------------
配置：
model_train_type = "flux-lora"
pretrained_model_name_or_path = "L:/stable-diffusion-webui/models/Stable-diffusion/Flux/flux_dev.safetensors"
ae = "L:/lora-scripts/sd-models/flux_aeSft.sft"
clip_l = "L:/lora-scripts/sd-models/clip_l.safetensors"
t5xxl = "L:/lora-scripts/sd-models/t5xxl_fp16.safetensors"
timestep_sampling = "sigmoid"
sigmoid_scale = 1
model_prediction_type = "raw"
discrete_flow_shift = 1
loss_type = "l2"
guidance_scale = 1
train_data_dir = "H:/AITrain/realaa"
prior_loss_weight = 1
resolution = "768,768"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 32
bucket_no_upscale = true
output_name = "aa_flux"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 5
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0005
text_encoder_lr = 0.00001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "PagedAdamW8bit"
network_module = "networks.lora_flux"
network_dim = 2
network_alpha = 16
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
max_token_length = 255
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
fp8_base = true
sdpa = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = true
===========
电脑是32G内存，改过16G显存的RTX3070，此电脑此前训练sd1.5和sdxl的Lora一切正常。

**Comment by Akegarasu** [comment]
#477
