### ISSUE TITLE
Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by petercham** [Akegarasu/lora-scripts#51]
反复重新安装过几次了，都会报这个错误。看install.bash里面确实有triton的安装指令

**Comment by HEXtoDEC** [comment]
手工进入虚拟环境安装。

**Comment by CresentMoon** [comment]
估计作者写漏掉了……

**Comment by czhang13-ua** [comment]
https://t.bilibili.com/232122178?type=2&comment_on=1
评论区有发triton在windows上的编译包。其实本质应该就是xformer更新后的一个可有可无的bug，一步步来就解决了。

**Comment by Akegarasu** [comment]
不影响训练
