### ISSUE TITLE
please fix bug

### ISSUE THREAD

**Issue by Zhang-Jiahui** [Akegarasu/lora-scripts#510]
when I use my model saved locally, it says the path is dir, which is not allowed.
But in fact, it can run normally.
![image](https://github.com/user-attachments/assets/871f2841-8a62-4107-9f76-aea4f93618b9)
It really troubles me, because what it says is not the same with what it runs.

Please fix the bug

**Comment by Akegarasu** [comment]
is `stable_diffusion_21_with_lora` a folder? what's in it?

**Comment by Zhang-Jiahui** [comment]
it's the same as noraml stable diffusion 2.1 base model, 
![image](https://github.com/user-attachments/assets/9dd2fe41-b128-46e4-8f22-311e6bab5421)
but I fuse lora with sd2.1 and save here
![image](https://github.com/user-attachments/assets/a4aad291-1a91-4c1d-a101-d26ae913bab8)
