### ISSUE TITLE
dreambooth method

### ISSUE THREAD

**Issue by Zhang-Jiahui** [Akegarasu/lora-scripts#512]
I choose the "专家" in LoRA column but it says "Using Dreambooth method". Is it running correctly?
![image](https://github.com/user-attachments/assets/e055402f-0645-420f-9edf-97bd5fee3126)
![image](https://github.com/user-attachments/assets/6a02c59c-f543-46b6-bd09-cbdf026bc883)

Another question: I have a image dataset containing more than 7w images. Before training, it takes about 7h to "get image size from name of cache files". Any solution to reduce the waiting time before training?

**Comment by Akegarasu** [comment]
it‘s running correctly. you can disable caching
