### ISSUE TITLE
avr_loss=nan 更新后一直是loss=nan 4070

### ISSUE THREAD

**Issue by wzgrx** [Akegarasu/lora-scripts#514]
steps:   0%|                                                                                 | 0/20000 [00:00<?, ?it/s]2024-09-20 17:24:23 INFO     unet dtype: torch.float16, device: cuda:0                             train_network.py:1058
                    INFO     text_encoder [0] dtype: torch.float16, device: cuda:0                 train_network.py:1064
                    INFO     text_encoder [1] dtype: torch.float16, device: cuda:0                 train_network.py:1064

epoch 1/10
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
2024-09-20 17:25:21 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:673
steps:   0%|                                                       | 5/20000 [01:59<132:17:56, 23.82s/it, avr_loss=nan]

**Comment by likelovewant** [comment]
刚开始而已...只要没报错就没问题

**Comment by wzgrx** [comment]
> 刚开始而已...只要没报错就没问题

好的，谢谢

**Comment by wzgrx** [comment]
steps:   2%|▊                                                   | 304/20000 [1:22:39<89:15:43, 16.32s/it, avr_loss=nan]
跑了几小时还是nan

**Comment by likelovewant** [comment]
说明速度很慢，我的跑了一晚上，目前31% ，之后再无更新。持续在跑，基本规律是过几个小时，这个log 会更新一次，如果没有更新则表示正在后台运行。每一个 epoch 6%左右，更新一次后，几个小时后又会更新 会跟新为 12% ... 以此步骤前进。当然我是在A卡上直接通过 zluda （ cuda）的形式在跑，再加上是flux 。速度很慢。如果 4070 N卡，只需要 把图片设置少一点 比如10 张，再设置10个 epoch的话，一个小时内应该可以训练完成。否则可能没有正确设置。原则上只要显卡在占用，且没有报错，大致是正在训练中...

log 进程类似如下...
steps:  31%|███▏      | 1250/4000 [9:39:10<21:14:11, 27.80s/it, avr_loss=0.255]
steps:  31%|███▏      | 1250/4000 [9:39:37<21:15:09, 27.82s/it, avr_loss=0.255]
[2024-09-20 02:02:54] [INFO] epoch 6/16
[2024-09-20 02:02:54] [INFO] 2024-09-20 02:02:54 INFO     epoch is incremented.            train_util.py:672
[2024-09-20 02:02:54] [INFO] current_epoch: 5, epoch: 6

**Comment by wzgrx** [comment]
> 说明速度很慢，我的跑了一晚上，目前31% ，之后再无更新。持续在跑，基本规律是过几个小时，这个log 会更新一次，如果没有更新则表示正在后台运行。每一个 epoch 6%左右，更新一次后，几个小时后又会更新 会跟新为 12% ... 以此步骤前进。当然我是在A卡上直接通过 zluda （ cuda）的形式在跑，再加上是flux 。速度很慢。如果 4070 N卡，只需要 把图片设置少一点 比如10 张，再设置10个 epoch的话，一个小时内应该可以训练完成。否则可能没有正确设置。原则上只要显卡在占用，且没有报错，大致是正在训练中...
> 
> log 进程类似如下... steps: 31%|███▏ | 1250/4000 [9:39:10<21:14:11, 27.80s/it, avr_loss=0.255] steps: 31%|███▏ | 1250/4000 [9:39:37<21:15:09, 27.82s/it, avr_loss=0.255] [2024-09-20 02:02:54] [INFO] epoch 6/16 [2024-09-20 02:02:54] [INFO] 2024-09-20 02:02:54 INFO epoch is incremented. train_util.py:672 [2024-09-20 02:02:54] [INFO] current_epoch: 5, epoch: 6

不是，昨天用老版本刚开始跑loss都是正常的，今天更新了一下，怎么设置参数都是loss nan

**Comment by wzgrx** [comment]
> > steps: 2%|▊ | 304/20000 [1:22:39<89:15:43, 16.32s/it, avr_loss=nan] 跑了几小时还是nan
> 
> 你好，我好像也是，我训练的sdxl的模型，结果跑了5天测试发现lora模型有没有几乎一样，请问你能试一试训练出的lora加载有效吗

不知道，我现在一直是loss nan

**Comment by likelovewant** [comment]
没有留意nan 这个关键数据。 翻了一下帖子 ，解决方法是把 fp16 改为 bf16就不会出现loss nan了。 具体要在参数中设置。可以尝试看看。

**Comment by wzgrx** [comment]
> 没有留意nan 这个关键数据。 翻了一下帖子 ，解决方法是把 fp16 改为 bf16就不会出现loss nan了。 具体要在参数中设置。可以尝试看看。

不行，最新版本，出事了十几种组合，全部都是nan，昨天正常用的的设置今天用还是nan，无语了，不知道怎么退回老版本

**Comment by likelovewant** [comment]
可以通过 git checkout commit  退回到任一时间点。 如 [commit list](https://github.com/Akegarasu/lora-scripts/commits/main/) 中 想要 切换到 Commits on Sep 19, 2024 的更改 5d7140214873375b69d9b2a3268867f7cab090b8 则在项目根目录下 直接 运行命令 git checkout 5d7140214873375b69d9b2a3268867f7cab090b8   则版本退回到修改的[ScheduleFree optimizer](https://github.com/Akegarasu/lora-scripts/commit/5d7140214873375b69d9b2a3268867f7cab090b8)， 以此类推，可以向前也可以回退。

**Comment by wzgrx** [comment]
> 可以通过 git checkout commit 退回到任一时间点。 如 [commit list](https://github.com/Akegarasu/lora-scripts/commits/main/) 中 想要 切换到 Commits on Sep 19, 2024 的更改 [5d71402](https://github.com/Akegarasu/lora-scripts/commit/5d7140214873375b69d9b2a3268867f7cab090b8) 则在项目根目录下 直接 运行命令 git checkout [5d71402](https://github.com/Akegarasu/lora-scripts/commit/5d7140214873375b69d9b2a3268867f7cab090b8) 则版本退回到修改的[ScheduleFree optimizer](https://github.com/Akegarasu/lora-scripts/commit/5d7140214873375b69d9b2a3268867f7cab090b8)， 以此类推，可以向前也可以回退。

懒得测试了，等修复了，先用kohya_ss，kohya_ss最新版使用正常

**Comment by Akegarasu** [comment]
更新

**Comment by wzgrx** [comment]
好的，谢谢大佬

**Comment by FlAmmmmING** [comment]
您好，请问是通病吗？我用macOS训练lora微调，我不管怎么设置optimizer和learning rate这个loss都是nan
