### ISSUE TITLE
If I want to train flux_lora, how should I fill in this model_type?如果要训练flux_lora，这个model_type该怎么填写呢?

### ISSUE THREAD

**Issue by kenic123** [Akegarasu/lora-scripts#519]
如果要训练flux_lora，这个model_type该怎么填写呢?
If I want to train flux_lora, how should I fill in this model_type?
![选区保存](https://github.com/user-attachments/assets/6d2f69e3-83de-4487-8cc8-deb24d0a7e9b)

**Comment by Akegarasu** [comment]
用ui训练 脚本暂时不支持

**Comment by kenic123** [comment]
感谢！！搞了两天没弄成。
