### ISSUE TITLE
继续训练功能支持，目前resume继续训练功能，试了一下还是全部重新训练一遍，是我理解错了吗

### ISSUE THREAD

**Issue by wzgrx** [Akegarasu/lora-scripts#524]
假如我从第16个epoch续训，
续训开始后，又会从epoch1开始计数，
直到max_train_epochs结束，
实际相当于训练了 16+max_train_epochs 个epoch，
这中间还会覆盖掉续训之前保存的safetensors文件，
感觉有点别扭。

可否改成：
从第16个epoch续训，
计数也从16开始，
直到max_train_epochs结束。
ps

**Comment by Akegarasu** [comment]
flux训练部分已经是你所说的样子了。其他部分请慢慢等待更新。

**Comment by wzgrx** [comment]
> flux训练部分已经是你所说的样子了。其他部分请慢慢等待更新。

好的，谢谢大佬

**Comment by cqarray** [comment]
![image](https://github.com/user-attachments/assets/a7a7e8c5-e736-42f1-95e9-9eee08ef6827)
希望新版本添加吧，可以从终止的状态下第N个epoch继续训练
