### ISSUE TITLE
安装时出错，请教大佬们！

### ISSUE THREAD

**Issue by wzh041** [Akegarasu/lora-scripts#525]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
sd-scripts 依赖安装失败。

**Comment by aigias** [comment]
install-cn.ps1文件，把目录改一下，
原：Set-Location .\scripts
改成：Set-Location .\sd-scripts

应该是这样。

**Comment by Akegarasu** [comment]
git clone --recurse-submodules https://github.com/Akegarasu/lora-scripts

**Comment by ilikeulinux** [comment]
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' sd-scripts 依赖安装失败。

按照下面，修改你的install.ps1
`$Env:HF_HOME = "huggingface"

if (!(Test-Path -Path "venv")) {
    Write-Output  "Creating venv for python..."
    python -m venv venv
}
.\venv\Scripts\activate

Write-Output "Installing deps..."
Set-Location .\scripts\stable
pip install torch==2.4.1 torchvision==0.19.1 --extra-index-url https://download.pytorch.org/whl/cu124
pip install -U -I --no-deps xformers==0.0.28.post1
pip install --upgrade -r requirements.txt

Set-Location ..
Set-Location ..
pip install --upgrade -r requirements.txt

Write-Output "Install completed"
Read-Host | Out-Null ;`
