### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by hansh2020** [Akegarasu/lora-scripts#544]
最新lora-scripts-v1.9.0-cu124更新报错，ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'，无法更新。我看了文件夹中有requirements.txt文件，不清楚是什么原因？请大佬指明方向，谢谢
（PS：lora包是今天刚下载的，以前的包没有发现这个问题
![Uploading Snipaste_2024-10-10_16-11-49.jpg…]()
）

**Comment by hansh2020** [comment]
补充图片
![Snipaste_2024-10-10_16-11-49](https://github.com/user-attachments/assets/d050e99e-af55-44ad-95e8-118654805ec0)
![Snipaste_2024-10-10_16-12-09](https://github.com/user-attachments/assets/67cfb2b1-e070-43c0-bb9f-7dedd95ec2da)

**Comment by Akegarasu** [comment]
不用管

**Comment by K-O-N-B** [comment]
> 不用管

我也是这个问题，按回车就退出了，所以也是安装成功了吗？

**Comment by K-O-N-B** [comment]
按运行最后这样：
![image](https://github.com/user-attachments/assets/cf913cb1-9f8b-4b86-969a-eaf6287215be)
