### ISSUE TITLE
执行打标签失败了，onnxruntime报错

### ISSUE THREAD

**Issue by WaWaSamuel** [Akegarasu/lora-scripts#545]
遇到个问题，执行打标签的报错，日志如下
[2024-10-11 12:19:35][SD-Trainer Installer]:: 初始化中
[2024-10-11 12:19:35][SD-Trainer Installer]:: SD-Trainer Installer 版本: v122
[2024-10-11 12:19:35][SD-Trainer Installer]:: 使用默认 HuggingFace 镜像源
[2024-10-11 12:19:35][SD-Trainer Installer]:: 启动 SD-Trainer 中
12:19:36-306243 INFO     Starting SD-Trainer Mikazuki GUI...
12:19:36-322165 INFO     Base directory: C:\Users\Admin\Downloads\SD-Trainer\lora-scripts, Working directory:
                         C:\Users\Admin\Downloads\SD-Trainer\lora-scripts
12:19:36-340151 INFO     Windows Python 3.10.11 C:\Users\Admin\Downloads\SD-Trainer\python\python.exe
12:19:36-340151 INFO     detected locale zh_CN, use pip & huggingface mirrors
12:19:38-103539 INFO     SD-Trainer Version: v1.10.0-3-g30659f3
12:19:38-113546 INFO     Starting tageditor...
12:19:38-129196 INFO     Starting tensorboard...
12:19:38-160411 INFO     Server started at http://127.0.0.1:28000
12:19:39-067263 INFO     Loading config from C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\assets\config.json
12:19:39-067263 INFO     Torch 2.3.0+cu118
12:19:39-099127 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:19:39-099127 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8192 Arch (8, 6) Cores 46
TensorFlow installation not found - running with reduced feature set.
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
found 6 image(s)
Loading wd14-vit-v3 model file from SmilingWolf/wd-vit-tagger-v3
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
  |     await response(scope, receive, send)
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 270, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 736, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 273, in wrap
    |     await func()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    |     return await super().stream_response(send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 262, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
    |     raise app_exc
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    |     raise exc
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 69, in app
    |     await response(scope, receive, send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 174, in __call__
    |     await self.background()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\background.py", line 43, in __call__
    |     await task()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\background.py", line 28, in __call__
    |     await run_in_threadpool(self.func, *self.args, **self.kwargs)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    |     return await future
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    |     result = context.run(func, *args)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 364, in on_interrogate
    |     ratings, tags = interrogator.interrogate(image)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 163, in interrogate
    |     self.load()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 142, in load
    |     from onnxruntime import InferenceSession
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    |     raise import_capi_exception
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    |     from .onnxruntime_pybind11_state import *  # noqa
    | ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\fastapi\applications.py", line 276, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 736, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 277, in __call__
    |     await wrap(partial(self.listen_for_disconnect, receive))
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 273, in wrap
    |     await func()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 250, in listen_for_disconnect
    |     message = await receive()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 564, in receive
    |     await self.message_event.wait()
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\asyncio\locks.py", line 214, in wait
    |     await fut
    | asyncio.exceptions.CancelledError: Cancelled by cancel scope 17f6a7634c0
    |
    | During handling of the above exception, another exception occurred:
    |
    | Exception Group Traceback (most recent call last):
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    |     await response(scope, receive, send)
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 270, in __call__
    |     async with anyio.create_task_group() as task_group:
    |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 736, in __aexit__
    |     raise BaseExceptionGroup(
    | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 273, in wrap
      |     await func()
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
      |     return await super().stream_response(send)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 262, in stream_response
      |     async for chunk in self.body_iterator:
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
      |     raise app_exc
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
      |     await self.app(scope, receive_or_disconnect, send_no_error)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
      |     raise exc
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
      |     await self.app(scope, receive, sender)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
      |     raise e
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
      |     await self.app(scope, receive, send)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 718, in __call__
      |     await route.handle(scope, receive, send)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 276, in handle
      |     await self.app(scope, receive, send)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\routing.py", line 69, in app
      |     await response(scope, receive, send)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\responses.py", line 174, in __call__
      |     await self.background()
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\background.py", line 43, in __call__
      |     await task()
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\background.py", line 28, in __call__
      |     await run_in_threadpool(self.func, *self.args, **self.kwargs)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
      |     return await anyio.to_thread.run_sync(func, *args)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
      |     return await get_async_backend().run_sync_in_worker_thread(
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
      |     return await future
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
      |     result = context.run(func, *args)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 364, in on_interrogate
      |     ratings, tags = interrogator.interrogate(image)
      |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 163, in interrogate
      |     self.load()
      |   File "C:\Users\Admin\Downloads\SD-Trainer\lora-scripts\mikazuki\tagger\interrogator.py", line 142, in load
      |     from onnxruntime import InferenceSession
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
      |     raise import_capi_exception
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
      |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
      |   File "C:\Users\Admin\Downloads\SD-Trainer\python\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
      |     from .onnxruntime_pybind11_state import *  # noqa
      | ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。
      +------------------------------------

**Comment by CharlinChen** [comment]
我遇到了同样的问题，网上查了一大圈，发现是onnxruntime版本不兼容导致的。
重新安装onnxruntime==1.17.1可以解决报错问题，但是用的是CPU推理很慢。
我尝试了各个版本，最终1.19.0可以适配GPU。
```
pip install onnxruntime==1.19.0
pip install onnxruntime-gpu==1.19.0
```
