### ISSUE TITLE
请问8G显存4060如何设置能正常训练SDXL的lora？

### ISSUE THREAD

**Issue by R-HUA** [Akegarasu/lora-scripts#566]

**Comment by cqarray** [comment]
顶一个，这边测试训练SDXL的lora会报错

**Comment by Akegarasu** [comment]
train u-net only

**Comment by cqarray** [comment]
测试4060显卡下的配置参数能正常跑SDXL-LORA
![image](https://github.com/user-attachments/assets/2763d5ac-4bbc-4e93-ae86-8b17e2c973e8)
