### ISSUE TITLE
似乎缺少sdxl的支持

### ISSUE THREAD

**Issue by ybaybaybaybayba** [Akegarasu/lora-scripts#568]
训练 sdxl 的 loratrain.ps1 会显示
 can't open file 'D:\\download\\lora-scripts-1.10.0\\scripts\\sdxl_train_network.py': [Errno 2] No such file or directory
似乎文件里面也确实没有这个，请问是否可以添加支持，如果需要手动下载能否提供链接

**Comment by Akegarasu** [comment]
update

**Comment by ybaybaybaybayba** [comment]
是前天刚下载的，看了下仓库里面好像也没有这个地址的文件
