### ISSUE TITLE
Advanced_SDXL_Train

### ISSUE THREAD

**Issue by DwyaneSkala** [Akegarasu/lora-scripts#588]
Today, after a complete reinstallation and cloning of your repository from GitHub, the settings in the advanced training for SDXL models have simply disappeared. How can this be fixed?
![2024-11-24_203537](https://github.com/user-attachments/assets/331f2ff5-e7d8-4050-b679-592d67fe9e4a)
Even after trying to restore saved templates, nothing happens — the panel on the right remains empty. Similarly, attempting to start training doesn't work; it simply doesn't start.
Everything was fine two days ago.

**Comment by Akegarasu** [comment]
The this project is currently undergoing refactoring, which might lead to some instability. If you encounter any bugs, please consider reverting to the v1.10.0 release.

If you can provide a complete set of saved parameter settings, it will help me fix the bug more quickly.

**Comment by Akegarasu** [comment]
please test the latest commit
