### ISSUE TITLE
min_snr_gamma support?

### ISSUE THREAD

**Issue by Kepler-16b** [Akegarasu/lora-scripts#59]
在看civit上的训练教程发现了这个算法：https://arxiv.org/abs/2303.09556
据说可以提高训练效率。不知道大佬有没有了解，训练脚本是否有计划/有必要加入这个？

**Comment by Georgebillion** [comment]
这个貌似我记得原有训练脚本有吧，这玩意没怎么用过

**Comment by Georgebillion** [comment]
真的要加的话，其实貌似也简单？我记得直接加一条命令就星？

**Comment by Akegarasu** [comment]
已添加
