### ISSUE TITLE
训练SDXL和Flux出现未知原因的失败

### ISSUE THREAD

**Issue by RoadToNowhereX** [Akegarasu/lora-scripts#591]
这是SDXL-lora的训练，最后一行的报错连个原因都没有，只提示了训练失败。训练flux-lora时也是一样，只有error没有原因。

09:45:09-267508 WARNING  No subdir found in data dir
09:45:09-268508 WARNING  No leagal dataset found. Try find avaliable images
09:45:09-270909 INFO     20 images found, 20 captions found
09:45:09-321881 INFO     Auto dataset created E:/AI/VisionModels/Lora-Scripts-v1.10.0/train/5_HsMolluSquare\5_zkz
09:46:32-806652 INFO     Training started with config file / 训练开始，使用配置文件:
                         E:\AI\VisionModels\Lora-Scripts-v1.10.0\config\autosave\20241129-094632.toml
09:46:32-810167 INFO     Task ab9209fc-735d-4777-a64e-7525872f496f created
2024-11-29 09:46:44 INFO     Loading settings from                                                    train_util.py:3745
                             E:\AI\VisionModels\Lora-Scripts-v1.10.0\config\autosave\20241129-094632.
                             toml...
                    INFO     E:\AI\VisionModels\Lora-Scripts-v1.10.0\config\autosave\20241129-094632  train_util.py:3764
2024-11-29 09:46:44 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
2024-11-29 09:46:45 INFO     update token length: 255                                             sdxl_train_util.py:159
                    INFO     Using DreamBooth method.                                               train_network.py:172
2024-11-29 09:46:46 INFO     prepare images.                                                          train_util.py:1573
                    INFO     found directory                                                          train_util.py:1520
                             E:\AI\VisionModels\Lora-Scripts-v1.10.0\train\5_HsMolluSquare\5_zkz
                             contains 20 image files
                    INFO     100 train images with repeating.                                         train_util.py:1614
                    INFO     0 reg images.                                                            train_util.py:1617
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1622
                    INFO     [Dataset 0]                                                              config_util.py:565
                               batch_size: 1
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 1024
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir:
                             "E:\AI\VisionModels\Lora-Scripts-v1.10.0\train\5_HsMolluSquare\5_zkz"
                                 image_count: 20
                                 num_repeats: 5
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: zkz
                                 caption_extension: .txt

                    INFO     [Dataset 0]                                                              config_util.py:571
                    INFO     loading image sizes.                                                      train_util.py:854
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 4986.69it/s]
                    INFO     make buckets                                                              train_util.py:860
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is   train_util.py:877
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計
                             算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                    train_util.py:906
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (1024, 1024), count: 100                             train_util.py:911
                    INFO     mean ar error (without repeats): 0.0                                      train_util.py:916
                    INFO     preparing accelerator                                                  train_network.py:225
accelerator device: cuda
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:30
                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:70
                             E:/AI/VisionModels/Lora-Scripts-v1.10.0/sd-models/sd_xl_base_1.0.safe
                             tensors
                    INFO     building U-Net                                                       sdxl_model_util.py:192
                    INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
09:47:15-747542 ERROR    Training failed / 训练失败

**Comment by cqarray** [comment]
是否使用了“sd_xl_base_1.0.safetensors” 做底模

**Comment by ucukertz** [comment]
@cqarray same problem. Not using “sd_xl_base_1.0.safetensors” as base model. Can we use other models?

**Comment by cqarray** [comment]
> @cqarray same problem. Not using “sd_xl_base_1.0.safetensors” as base model. Can we use other models?

Training SDXL-LORA requires the use of SDXL's base model, otherwise an error will be reported
