### ISSUE TITLE
为何安装不上去呢？看起来也没冲突依赖项呀

### ISSUE THREAD

**Issue by yitao2020** [Akegarasu/lora-scripts#598]
![IMG_3196](https://github.com/user-attachments/assets/931342ce-9f65-459d-9e37-931deebbeb77)
![Uploading 956182724f3fdad08c2b36522e53379e.jpg…]()

**Comment by cqarray** [comment]
尝试切换一下pip的源或者，或者选个好的网络，看报错提示在安装过程中找不到版本

**Comment by yitao2020** [comment]
仔细排查发现是调用了另外一个文件夹的python
