### ISSUE TITLE
一个可以优化的无影响的错误显示

### ISSUE THREAD

**Issue by NaughtDZ** [Akegarasu/lora-scripts#62]
windows跑这个脚本会提示：
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
基本上每次启动一轮ecopoch都会反复显示很多很多遍
![image](https://user-images.githubusercontent.com/37768911/229858759-451f203c-4d4a-4a52-932f-fe4b2ed3737a.png)
但是不会影响训练。
经谷歌查找,Triton这个组件是不适用于windows而是给linux用的，所以windows报这个错误其实没任何意义，应该有个途径把它屏蔽掉，不然有点浪费时间（不过相比于整个训练，也不是浪费太多时间）

**Comment by UnsleepingCat** [comment]
但是这个东西会一直出现，非常恼火。不知道windows能不能支持安装一下，至少别在出现了

**Comment by Georgebillion** [comment]
无法安装，该包是linux下的依赖包 已知在pt2.0版本会出现，如果嫌烦请直接回退到1.3.X版本

**Comment by UnsleepingCat** [comment]
> 

也就是说这是pytorch版本问题，而不是script的问题吧？好的。那就这样了

**Comment by NaughtDZ** [comment]
> 无法安装，该包是linux下的依赖包 已知在pt2.0版本会出现，如果嫌烦请直接回退到1.3.X版本

所以说能不能让它在windows环境下不检测这个组件存不存在呢？每个epoch之间都要检测好几遍，对于重复少，epoch多的训练，这玩意浪费的时间简直太恐怖了。

**Comment by Akegarasu** [comment]
不影响速度
