### ISSUE TITLE
pip install -U -I --no-deps xformers==0.0.17 下载失败

### ISSUE THREAD

**Issue by NINTING** [Akegarasu/lora-scripts#64]
ERROR: Could not find a version that satisfies the requirement xformers==0.0.17 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16)
ERROR: No matching distribution found for xformers==0.0.17

我的python版本为Python 3.11.2
是需要3.10 吗还是需要按照其他插件

**Comment by martellz** [comment]
python版本: 3.8 - 3.10

**Comment by martellz** [comment]
> 

看起来不是xformers的问题，尝试：pip install --upgrade pip setuptools wheel，

**Comment by Flywolfs** [comment]
官方源：pip install --upgrade xformers==0.0.17 -i https://pypi.python.org/simple

**Comment by Georgebillion** [comment]
xfromers官方有介绍相关命令 尝试 pip install -U --pre xfromers

**Comment by Akegarasu** [comment]
镜像源的问题，上游已修复
