### ISSUE TITLE
模型训练时下载pytorch_model.bin报错

### ISSUE THREAD

**Issue by myhaha** [Akegarasu/lora-scripts#65]
服务器上安装完环境开始训练模型的时候走到 Downloading (…)"pytorch_model.bin";步骤的时候一直下载不下来这个文件，显示网络连接问题，但是机器网络并没有太大问题，请问下该如何操作呢
![image](https://user-images.githubusercontent.com/38137923/230600774-eea4f14b-4e01-4d23-abbe-bfc1d12815cf.png)
![image](https://user-images.githubusercontent.com/38137923/230600805-e9deaf2b-df15-4caf-97d5-0ac0b507ea63.png)

**Comment by Georgebillion** [comment]
如果没猜错的话，这个文件需要科学上网下载，建议挂梯子 黄脸在部分地区会出现直连无法使用的情况 处于正常现象

**Comment by NuanYangDaDa** [comment]
没梯子就全局换源    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
