### ISSUE TITLE
mac用不了，怎么可以用上呢？

### ISSUE THREAD

**Issue by Zhaoxinak** [Akegarasu/lora-scripts#68]
希望mac能用上，给一个方法

**Comment by Georgebillion** [comment]
mac 你用sh也不行吗？已知MAC和linux代码差别不大，如果不行请回复

**Comment by dzg123** [comment]
> mac 你用sh也不行吗？已知MAC和linux代码差别不大，如果不行请回复

mac用sh xformers安装各种报错
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64

**Comment by Georgebillion** [comment]
> > mac 你用sh也不行吗？已知MAC和linux代码差别不大，如果不行请回复
> 
> mac用sh xformers安装各种报错 ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64

xformers啊，要不去看看官方的安装方法？我记得关于这块他们有写 而且 Mac开终端的话，你开虚拟环境不应该会装不上吧？

**Comment by nangongamo** [comment]
训练需要N卡，mac不支持的。
