### ISSUE TITLE
安裝顯示這個

### ISSUE THREAD

**Issue by KCopgg696** [Akegarasu/lora-scripts#69]
.\venv\Scripts\activate : The term '.\venv\Scripts\activate' is not recognized as the name of a cmdlet, function, scrip
t file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
 and try again.
At D:\SD-AMD\lora\lora-scripts\install.ps1:9 char:1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Georgebillion** [comment]
依赖安装装了吗？运行一下install-cn.ps1

**Comment by Akegarasu** [comment]
检查python是否正确安装再运行install.ps1脚本。
