### ISSUE TITLE
train.sh文件中关于save_state的bug

### ISSUE THREAD

**Issue by WSH032** [Akegarasu/lora-scripts#72]
https://github.com/Akegarasu/lora-scripts/blob/0fe5ab9c3c064af9b62df9ca41c266a4dc430c0d/train.sh#L86
应为`if [ $save_state == 1 ]; then extArgs+=("--save_state"); fi`

**Comment by Georgebillion** [comment]
这个已经有人提了PR而且已经合并了，重新更新代码
