### ISSUE TITLE
优化器问题

### ISSUE THREAD

**Issue by shiminxuan003** [Akegarasu/lora-scripts#76]
linux 升级torch2.0后训练优化器选择AdamW8bit报错
![image](https://user-images.githubusercontent.com/57788912/230856402-c6a90d5a-e2af-4cf2-b876-ba93a02d2a85.png)
优化器改为其他则正常运行，请问大佬什么原因

**Comment by 4nth0ny1130** [comment]
cuda12的版本过高,[torch官方](https://pytorch.org/)目前最高支持到cuda11.8,尝试降低cuda版本来解决这个错误
