### ISSUE TITLE
主分支删除train.ps1中的optimizer_type是出于何种考量？

### ISSUE THREAD

**Issue by 4nth0ny1130** [Akegarasu/lora-scripts#77]
删除该参数optimizer就只能用lion或者AdamW8bit了。如果是出于这个项目是偏开箱即用的考量我认为应该再加个DAdaptation，DAdaptation不需要调整学习率。

**Comment by Georgebillion** [comment]
？PS1部分的代码已经交PR等待merge了，新代码已经写进了优化器类型

**Comment by Georgebillion** [comment]
> 删除该参数optimizer就只能用lion或者AdamW8bit了。如果是出于这个项目是偏开箱即用的考量我认为应该再加个DAdaptation，DAdaptation不需要调整学习率。

我记得曾经问过，貌似是要换使用方法，新的貌似已经在等审核过了

**Comment by Akegarasu** [comment]
从来没删除过，sh里面是新加的。。

**Comment by 4nth0ny1130** [comment]
> 从来没删除过，sh里面是新加的。。

好吧,我的问题,搞混了
