### ISSUE TITLE
Failed to install xformers==0.0.14.dev0

### ISSUE THREAD

**Issue by YuriWu** [Akegarasu/lora-scripts#8]
When I ran the install-cn.ps1, it failed at installing xformers.

The install cmd:
`pip install -U -I --no-deps https://jihulab.com/api/v4/projects/82097/packages/pypi/files/e8508fe14c8f2552a822f5e6f5620b24fdd4ba3129c2a31a39b56425bcc023bc/xformers-0.0.14.dev0+torch12-cp310-cp310-win_amd64.whl`

The error msg:
`ERROR: xformers-0.0.14.dev0+torch12-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.`

I tried to manually install that version via pip, but no version matches:
`
pip install xformers==0.0.14.dev0
ERROR: Could not find a version that satisfies the requirement xformers==0.0.14.dev0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17.dev448, 0.0.17.dev449, 0.0.17.dev451, 0.0.17.dev461, 0.0.17.dev464)
ERROR: No matching distribution found for xformers==0.0.14.dev0
`

Also tried some .whl in [this page](https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases). Still no luck.

Could anyone help?

**Comment by Akegarasu** [comment]
what's your python version?
