### ISSUE TITLE
ERR：ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by costs** [Akegarasu/lora-scripts#82]
ai@ai-System-Product-Name:~/lora-scripts$ bash train.sh
train.sh: 第 66 行： [: ==: 需要一元运算符
Traceback (most recent call last):
  File "/home/ai/.local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/ai/.local/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/ai/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 28, in <module>
    import torch
  File "/usr/local/lib/python3.10/dist-packages/torch-2.0.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

ai@ai-System-Product-Name:~/lora-scripts$ echo $PATH
/home/ai/.local/bin:/usr/local/cuda-12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ai@ai-System-Product-Name:~/lora-scripts$ nvidia-smi
Sat Apr 15 03:45:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:0B:00.0 Off |                  Off |
|  0%   48C    P8    26W / 450W |   2546MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2692      G   /usr/lib/xorg/Xorg                 90MiB |
|    0   N/A  N/A      3336      G   /usr/bin/gnome-shell               61MiB |
|    0   N/A  N/A    224563      C   python3                          2390MiB |
+-----------------------------------------------------------------------------+

**Comment by Georgebillion** [comment]
cuda12啊，不清楚是不是cuda过高了？

**Comment by Georgebillion** [comment]
而且我记得现在torch不支持cuda12，最高也是cuda11.8,装一个11.8试一下
