### ISSUE TITLE
two 2080ti,但是知识调用了一块

### ISSUE THREAD

**Issue by fangbo6699** [Akegarasu/lora-scripts#9]
two 2080ti,但是知识调用了一块，如何设置调用两块同时训练

**Comment by Akegarasu** [comment]
正常来说默认应该是会用上的

**Comment by lam2018** [comment]
> 正常来说默认应该是会用上的

作者你好，请问在哪里可以更改吗。我的两块A100在LORA训练时也是只有一块有负载。

**Comment by martellz** [comment]
https://github.com/kohya-ss/sd-scripts/pull/165

**Comment by Georgebillion** [comment]
已经提交相关PR等待作者审核
