### ISSUE TITLE
Error：No module named 'triton'【run install-cn.ps1 success ,run train.ps1 error】

### ISSUE THREAD

**Issue by AnubisCL** [Akegarasu/lora-scripts#92]

**Comment by AnubisCL** [comment]
![image](https://user-images.githubusercontent.com/50880855/233728993-5f1b0d31-837f-4022-8e3e-fad55058cd4c.png)

triton 在win10、win11 上怎么安装？只能在docker上安装吗？

win10上
pip install triton
和
pip install -U --pre triton
都不行。

https://github.com/openai/triton/issues/1560

**Comment by Akegarasu** [comment]
windows上triton没用 不用管
