### ISSUE TITLE
可以训练2.0以上的model吗？

### ISSUE THREAD

**Issue by tonyWang-001** [Akegarasu/lora-scripts#94]
我看参数有训练2.0以上模型的说明，该怎么调用呢？我直接训练出来的效果很差，全是噪音

**Comment by Akegarasu** [comment]
可以

**Comment by gaogg** [comment]
+1，请问参数应该怎么设置？parameterization是要设成1？

**Comment by MMY1994** [comment]
@tonyWang-001 你好，我也是这种情况，生成的全是噪音，请问你这边解决了么
