### ISSUE TITLE
关于Dadaption优化器的报错

### ISSUE THREAD

**Issue by WSH032** [Akegarasu/lora-scripts#96]
- 有人提到更新后的Dadaption会报错，主要的报错信息为
`RuntimeError: Setting different lr values in different parameter groups is only supported for values of 0`

- 经测试，发现unet_lr != text_lr时出现这个问题，终端输出提示
`when multiple learning rates are specified with dadaptation (e.g. for Text Encoder and U-Net), only the first one will take effect / D-Adaptationで複数の学習率を指定した場合（Text EncoderとU-Netなど）、最初の学習率のみが有効になります: lr=0.5`

参考[https://github.com/kohya-ss/sd-scripts/issues/274](https://github.com/kohya-ss/sd-scripts/issues/274)和[https://github.com/kohya-ss/sd-scripts/issues/181](https://github.com/kohya-ss/sd-scripts/issues/181)

- 似乎现在使用Dadaption时只能指定同一个学习率？
```
network_dim=16
network_alpha=8
unet_lr=0.5
text_encoder_lr=0.5
optimizer_type="DAdaptation"
optimizer_args=["decouple=True", "weight_decay=1.0"]
lr_scheduler="constant"
min_snr_gamma=5
```

**Comment by Akegarasu** [comment]
是这样

**Comment by kooriki** [comment]
Champion!!!
