### ISSUE TITLE
A matching Triton is not available, some optimizations will not be enabled.Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by carloon1118** [Akegarasu/lora-scripts#99]
![image](https://user-images.githubusercontent.com/31775094/233982191-02e9d473-358d-4561-90bf-c14a272ba4d8.png)

**Comment by carloon1118** [comment]
![image](https://user-images.githubusercontent.com/31775094/233982574-39dd4bf0-16dd-497b-a2cd-f9ad29ef206a.png)

**Comment by carloon1118** [comment]
速度堪忧，加速功能失效？

**Comment by lzy516** [comment]
出现

A matching Triton is not available, some optimizations will not be enabled.

Error caught was: No module named 'triton'

可以不用管，

但是做了下面步骤，可以不看见报错，心情会好一点。

1.下载https://drive.google.com/file/d/1e4bOU2SDj6TB12uUKG2QcQM8SgMZRVD9/view?usp=sharing，复制文件到根目录，

2.激活venv

3.pip install triton-2.0.0-cp310-cp310-win_amd64.whl


用txt做一个批处理文件，复制以下代码：.\venv\Scripts\python.exe -m pip install triton-2.0.0-cp310-cp310-win_amd64.whl
pause
然后后缀名改为.bat，然后双击执行就可以了，直接下载安装。

**Comment by martellz** [comment]
windows没有triton
如果速度真有下降可以尝试更改torch和xformers版本

**Comment by liuzhao6** [comment]
> 
谢谢大佬的帮助，我遇到了类似: No module named 'xxx'这样的问题，然后我在训练根目录执行./venv/Scripts/python.exe -m pip install xxx解决了报错.应该是我以前安装的包在本机了，需要安装在虚拟环境下

**Comment by LINSUISHENG034** [comment]
It's worked for me.
https://github.com/Akegarasu/lora-scripts/issues/51#issuecomment-1501024876
